### ISSUE TITLE
feat: let users change default installation directory `janroot`

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1010]
# Goal
Allow users to change the app data folder in settings

# Design
Full design flow: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=2270-285004&mode=design&t=bQyiFG80Dcr1XlBm-4

## User flow
1. Go to `Settings / Advanced Settings`
2. See `Jan Data Folder` 
3. Users can:
- Show Jan Data Folder in Finder.
- Relocate Jan Data Folder by clicking on the edit button.

<img width="917" alt="Screenshot 2024-01-16 at 2 00 31 PM" src="https://github.com/janhq/jan/assets/89722390/5b915946-7acc-4826-9dd0-013b4636af37">

4. Users need to confirm if they want to relocate Jan App Folder request.

<img width="859" alt="Screenshot 2024-01-16 at 2 04 52 PM" src="https://github.com/janhq/jan/assets/89722390/c019713f-3cdf-4620-b8f7-1933712fd39f">

5. Users can see the progress of relocating Jan App Folder.

<img width="870" alt="Screenshot 2024-01-16 at 2 05 08 PM" src="https://github.com/janhq/jan/assets/89722390/e81cd4ac-2079-4448-bda4-08e218f0cea1">

6. The app will restart upon completion.

<img width="868" alt="Screenshot 2024-01-16 at 2 07 23 PM" src="https://github.com/janhq/jan/assets/89722390/66d8fab1-d718-4f58-aeac-fbc88d2810fa">

## Error scenarios
1. Folder is not available / does not have enough space

<img width="835" alt="Screenshot 2024-01-16 at 2 08 04 PM" src="https://github.com/janhq/jan/assets/89722390/6d32ddee-87ae-4bd3-b4cf-0c74c861352b">

2. A more generic error for other disrupting cases 

<img width="923" alt="Screenshot 2024-01-16 at 2 08 38 PM" src="https://github.com/janhq/jan/assets/89722390/47f05552-5e82-4060-943b-7894c55e2eab">

**Comment by imtuyethan** [comment]
# Todo
- [ ] @louis-jan Allow users to choose the default folder configurable on **installation**
- [ ] Allow users to change the model folder directory
- [ ] Allow users to change the installation directory 


# 1. Allow users to choose the default folder configurable on installation
For @louis-jan @namchuai to configure

# 2. Allow users to change the model folder directory
Full design flow: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=2052-155715&mode=design&t=ZWZGgzJWErWbLVBs-4

_Preview:_
Users should be able to change model directory in `settings/models`

<img width="1430" alt="Screenshot 2024-01-09 at 5 20 14 PM" src="https://github.com/janhq/jan/assets/89722390/ffa2d41d-00fe-4321-8c59-3e1d9ffa80d3">

<img width="1429" alt="Screenshot 2024-01-09 at 5 21 44 PM" src="https://github.com/janhq/jan/assets/89722390/101529fd-a23f-422a-b96c-1ab7a8ee4566">

#### Error when the folder is not available:

![Settings](https://github.com/janhq/jan/assets/89722390/44ef8b18-79a6-4618-9bd3-4b8b01ca6df0)

#### Side note

<img width="595" alt="Screenshot 2024-01-09 at 5 27 05 PM" src="https://github.com/janhq/jan/assets/89722390/c11727b6-bd02-46ec-a031-de930d09fef5">


# 3. Allow users to change the installation directory 
Similarly for changing app directory 
Full design flow: 
https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=2060-186972&mode=design&t=ZWZGgzJWErWbLVBs-4

![Data privacy](https://github.com/janhq/jan/assets/89722390/f6b88262-3d62-4218-b597-5852d6dd5bc9)

**Comment by 0xSage** [comment]
I noticed we're also letting users change model directory. 

Questions: 
1. Does that add engineering complexity?
2. Does that fundamentally solve the users' issue where they have **unique & unpredictable ways of storing model binaries**, and want a way to symlink into specific model paths?
3. What engineering challenges, edge cases, arise, as a result of decoupling `/models` from `janroot`?

**Comment by louis-jan** [comment]
1. Migration will be a challenge where users have downloaded models. We need to relocate the entire directory. There is no fs progress sync for now. Should ask user for the action?
2. Yes
3. Decoupling /models from janroot would introduce two kinds of settings: abs vs relv paths (to jan root). We should allow users to set the Electron app data path as well.
Edge cases:
- AppData (default created by electron) accidentally removed by users, the global config file is there.

Delete app: we should gather all possible locations and ask the user before cleaning them. However, it seems that only Windows users are familiar with un-installers. On MacOS, they will likely not open the dmg file again to run uninstall script, they will prob just delete the jan.app.

**Comment by 0xSage** [comment]
> * Delete app: we should gather all possible locations and ask the user before cleaning them. However, it seems that only Windows users are familiar with un-installers. On MacOS, they will likely not open the dmg file again to run uninstall script, they will prob just delete the jan.app.

This is my main concern with increasing the scope of this ticket to let users fork off ~/models. 

This means mac users will be left with many orphaned `model.jsons` even though they deleted the app. Bad practice.

Let's do one thing at a time. Reduce complexity please.

**Comment by sukesh-ak** [comment]
LM Studio has this simple option to relocate local models folder.
![image](https://github.com/janhq/jan/assets/53081362/910829d5-ff5b-41c2-ac61-876da2fd8c33)

In case of Jan, it could be the entire data-root which also contains all the folders like `assistants`, `models` etc.

**Comment by imtuyethan** [comment]
# Design
Full design flow: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=2270-285004&mode=design&t=e4y3O3QchhS4m1GT-4
cc @louis-jan @urmauur 

# Preview
<img width="899" alt="Screenshot 2024-01-11 at 6 51 47 PM" src="https://github.com/janhq/jan/assets/89722390/5ed7ecc5-764f-433d-89af-596f22ef85a7">

![Data privacy](https://github.com/janhq/jan/assets/89722390/7b6dcfea-60f5-4866-af09-41a6c36b9a9a)

![Error](https://github.com/janhq/jan/assets/89722390/80ba93e3-8fb1-4447-b372-99f665280fb0)

**Comment by imtuyethan** [comment]
Archive @0xSage's original comment:

**Problem**
I have the code at ~, and now the app backs up data at ~. 
I'd like to designate another place for app data persistence. 

![Uploading image.png…]()

**Success Criteria**
A clear and concise description of what you want to happen.
1. I go to settings
2. I type in a new directory
3. I confirm I want to `Change App Data Location`
4. I see a transition/in progress state (if any)
6. I get a confirmation it was done
7. I get a prompt to restart the App (if needed)
8. Upon returning to settings, I see my new path ++ shortcut to open up folder in the new location

**Not in scope**
- Letting users change `models` folder
- I'd prefer we allow #1381 before letting users fork off folders
- An Obsidian Vault-like onboarding flow guiding users through choosing vault locations

**Additional context**
Add any other context or screenshots about the feature request here.
