### ISSUE TITLE
epic: New Thread Settings Panel with correct file overwrites

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1044]
## Motivation

- Right panel was missing params / sub sections
- UI was confusing, because even though Right Panel edits affect `thread.json` only, users felt like they were editting `model.json`, `assistant.json`

## Designs
https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=112-37497&mode=design&t=s5Td4SkT9LRH86bS-0

## Stories

1. Users can edit all of the parameters in `thread.json` except the following: 
  - `id`: show but gray out
  - `object`: dont show in UI
  - assistants[0] > defaults to Jan (obv this can't be editted)
  - `assistants[0].assistant_id`: don't show in UI
  - `created`: don't show in UI
  - `updated`: don't show in UI
  - `metadata`: don't show in UI
> This might deviate a bit from what's rendered in designs, please follow this guide

2. Users can refine model configs in the following sections, with changes affecting `thread.json`
  - `Inference parameters`
  - `Model parameters`
  - `engine parameters`

3. Remove autosave. Users must click save button. 

4. Basic error handling around users not saving changes in Thread Settings

5. When users edit the following sections, button must say "save & reload" because it requires models to be reloaded at nitro level. Otherwise, button just says "save"
  - `Model params`
  - `Engine params`

6. Sections have tooltips: 
  - Do your best to put in placeholder
  - @tikikun @hahuyhoang411  for the final copy during QA

7. Change the Assistant & Model section Dropdowns to "edit global defaults for [model/assistant name]" rather than what we had before. See designs.

8. If users edit `assistant.json`, or `model.json` directly, the overwrites take effect for subsequent new threads
  - #1203 : assistant default params should be changeable via file
  - Same for `model.json`
  - **When properties are undefined**, they follow inheritance rule: `thread` inherits `assistant.json`, inherits `model.json`

## Tasklist

- [x] https://github.com/janhq/internal/issues/66
- [ ] #1212 
- [x] #1190 (quick UI fix, though may not be relevant anymore bc you guys want to allow mid-thread model switching?)
- [x]  #1129 @hieu-jan 
- [x] #1189 (Needs a decision: `won't fix`, `sort alphabetically within section`, `reference default model.jsons`, etc. Up to app pod.
- [x] #1183 
- [x] #1250 @urmauur 

## Not in Scope
- #1175 
- Possibly #1189 if the decision is `won't fix`
- Feel free to drag other tasks here.

**Comment by 0xSage** [comment]
Closing this epic, other than a dangling QA issue. 

Great job @namchuai
