### ISSUE TITLE
docs: update Guide Starting a Thread

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1129]
**Pages**
Starting a Thread: https://jan.ai/guides/chatting/start-thread/

**Success Criteria**
- [x] User can successfully chat with a model in a thread
- [x] User can change assistant instructions

**Checklist**
Content that should be covered
- [x] How to starting a thread and cover outline below
- [x] Guides on how to use the Jan application, with GIFs. For end users who are directly using Jan. 
- [x] Related keywords should be updated.
- [x] Related images should be optimized.

**Outline**
- Choosing an assistant
- Setting assistant instructions
    -   At thread level
    -   Globally, as default
- Choosing a model
- Customizing model params (thread level)
- Customizing engine params

**Additional context**
TBD
