### ISSUE TITLE
docs: update Guide Uploading Images

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1131]
**Pages**
Uploading Images: https://jan.ai/guides/chatting/upload-images/

**Success Criteria**
Content that should be covered
- [ ] How to uploading images.
- [ ] Guides on how to use the Jan application, with GIFs. For end users who are directly using Jan. 
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

**Additional context**
TBD

**Comment by 0xSage** [comment]
Dupe of #1130
