### ISSUE TITLE
docs: update Guide Manage Chat History

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1132]
**Pages**
Manage Chat History  | Jan: https://jan.ai/guides/chatting/manage-history/

**Success Criteria**
Content that should be covered
- [x] How to manage chat history
- [x] Guides on how to use the Jan application, with GIFs. For end users who are directly using Jan.
- [x] Related keywords should be updated.
- [x] Related images should be optimized.

**Additional context**
TBD
