### ISSUE TITLE
docs: update Guide Install Models from the Hub

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1133]
**Pages**
Install Models from the Hub: https://jan.ai/guides/using-models/install-from-hub/

**Success Criteria**
Content that should be covered
- [x] How to install models from the hub
- [x] Guides on how to use the Jan application, with GIFs. For end users who are directly using Jan. 
- [x] Related keywords should be updated.
- [x] Related images should be compressed.

**Additional context**
TBD

**Comment by hieu-jan** [comment]
Finalized this docs via #1450 and #1454.
