### ISSUE TITLE
docs: update Guide Customize Model Defaults

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1134]
**Pages**
Customize Model Defaults: https://jan.ai/guides/using-models/customize-models/

**Success Criteria**
Content that should be covered
- [ ] How to customize model defaults
- [ ] Guides on how to use the Jan application, with GIFs. For end users who are directly using Jan.
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

**Additional context**
TBD
