### ISSUE TITLE
docs: update Guide Using Models

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1135]
**Pages**
Page: https://jan.ai/guides/using-models/

**Success Criteria**
Content that should be covered
- [x] Overall guide of Using model 
- [x] Guides on how to use the Jan application, with GIFs. For end users who are directly using Jan.
- [x] Related keywords should be updated.
- [x] Related images should be compressed.

**Additional context**
TBD
