### ISSUE TITLE
docs: update Guide Chatting

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1136]
**Pages**
Page: https://jan.ai/guides/chatting/

**Success Criteria**
Content that should be covered
- [x] Overall guide of Chatting
- [x] Guides on how to use the Jan application, with GIFs. For end users who are directly using Jan.
- [x] Related keywords should be updated.
- [x] Related images should be optimized. 

**Additional context**
TBD
