### ISSUE TITLE
docs: update Guide Using the Local Server

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1137]
**Pages**
Page: https://jan.ai/guides/using-server/

**Success Criteria**
Content that should be covered
- [ ] Overall guide of Using the Local Server 
- [ ] Guides on how to use the Jan application, with GIFs. For end users who are directly using Jan.
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

Include: 
- How to turn on server in settings
- How to access server docs vial 1337/docs
- Warning about how api-reference is outdated (we should probably turn this page off for now)
- Warning about how other in app features (like threads chatting ux) might be broken while using server

**Additional context**
TBD

**Comment by hieu-jan** [comment]
Merged #1924 as first temporary docs for Using Local API Server

**Comment by hieu-jan** [comment]
This issue is completed. New docs is available on main website.
