### ISSUE TITLE
docs: update Guide Connect to Server

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1138]
**Pages**
Page: https://jan.ai/guides/using-server/server/

**Success Criteria**
Content that should be covered
- [ ] How to connect to server
- [ ] Guides on how to use the Jan application, with GIFs. For end users who are directly using Jan.
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

**Additional context**
TBD

**Comment by 0xSage** [comment]
dupe of #1137
