### ISSUE TITLE
docs: update Guide Using Extensions 

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1139]
**Pages**
Page: https://jan.ai/guides/using-extensions/

**Success Criteria**
Content that should be covered
- [x] Overall guide of Using extensions 
- [x] Guides on how to use the Jan application, with GIFs. For end users who are directly using Jan.
- [x] Related keywords should be updated.
- [x] Related images should be compressed.

**Additional context**
TBD

**Comment by 0xSage** [comment]
merging #1140  and #1141 into this

**Comment by hieu-jan** [comment]
Solved via PR #1657
