### ISSUE TITLE
docs: update Guide Import Extensions

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1140]
**Pages**
Page:https://jan.ai/guides/using-extensions/import-extensions/

**Success Criteria**
Content that should be covered
- [ ] Guide should covers on how to import extensions
- [ ] Guides on how to use the Jan application, with GIFs. For end users who are directly using Jan.
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

**Additional context**
TBD

**Comment by 0xSage** [comment]
Dupe of #1040
