### ISSUE TITLE
docs: update Guide Extension Settings

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1141]
**Pages**
Page: https://jan.ai/guides/using-extensions/extension-settings/

**Success Criteria**
Content that should be covered
- [ ] How to configure setting for extensions
- [ ] Guides on how to use the Jan application, with GIFs. For end users who are directly using Jan.
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

**Additional context**
TBD
