### ISSUE TITLE
docs: update Developer Docs Build an Assistant

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1144]
**Pages**
Build an Assistant: https://jan.ai/developer/build-assistant/

**Success Criteria**
Content that should be covered
- [ ] In this tutorial, you will learn how to start build an assistant on Jan
- [ ] Developer docs on how to extend Jan. These pages are about what people can build. It should sufficiently outlining the overarching architecture to empower developers to effectively develop upon it.
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

**Additional context**
TBD
