### ISSUE TITLE
docs: update Developer Anatomy of an Assistant

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1146]
**Pages**
Anatomy of an Assistant: https://jan.ai/developer/build-assistant/assistant-anatomy/

**Success Criteria**
Content that should be covered
- [ ] This docs should include an overview of assistant.json and assistant file structure.
- [ ] Developer docs on how to extend Jan. These pages are about what people can build. It should sufficiently outlining the overarching architecture to empower developers to effectively develop upon it.
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

**Additional context**
TBD
