### ISSUE TITLE
docs: update Developer Package Your Assistant

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1147]
**Pages**
Package your Assistant: https://jan.ai/developer/build-assistant/package-your-assistant/

**Success Criteria**
Content that should be covered
- [ ] This docs should includes packaging, exporting, sharing and publishing an assistant to Hub. 
- [ ] Developer docs on how to extend Jan. These pages are about what people can build. It should sufficiently outlining the overarching architecture to empower developers to effectively develop upon it.
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

**Additional context**
TBD
