### ISSUE TITLE
docs: update Developer Your First Engine

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1149]
**Pages**
Your First Engine: https://jan.ai/developer/build-engine/your-first-engine/

**Success Criteria**
Content that should be covered
- [ ] This docs should include a quick start on how to build your first engine
- [ ] Developer docs on how to extend Jan. These pages are about what people can build. It should sufficiently outlining the overarching architecture to empower developers to effectively develop upon it.
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

**Additional context**
TBD
