### ISSUE TITLE
docs: update Developer Package Your Engine

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1150]
**Pages**
Package your Engine: https://jan.ai/developer/build-engine/package-your-engine/

**Success Criteria**
Content that should be covered
- [ ] This docs should includes packaging, exporting, sharing and publishing your engine.
- [ ] Developer docs on how to extend Jan. These pages are about what people can build. It should sufficiently outlining the overarching architecture to empower developers to effectively develop upon it.
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

**Additional context**
TBD
