### ISSUE TITLE
docs: update Developer Build an Extension

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1151]
**Pages**
Build an Extension: https://jan.ai/developer/build-extension/

**Success Criteria**
Content that should be covered
- [ ] In this tutorial, you will learn how to start build an extension on Jan
- [ ] Developer docs on how to extend Jan. These pages are about what people can build. It should sufficiently outlining the overarching architecture to empower developers to effectively develop upon it.
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

**Additional context**
TBD
