### ISSUE TITLE
docs: update Developer Your First Extension

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1152]
**Pages**
Your First Extension: https://jan.ai/developer/build-extension/your-first-extension/

**Success Criteria**
Content that should be covered
- [ ] This docs should include a quick start on how to build your first extension
- [ ] Developer docs on how to extend Jan. These pages are about what people can build. It should sufficiently outlining the overarching architecture to empower developers to effectively develop upon it.
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

**Additional context**
TBD
