### ISSUE TITLE
docs: update Developer Anatomy of an Engine

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1154]
**Pages**
Anatomy of an Engine: https://jan.ai/developer/build-engine/engine-anatomy/

**Success Criteria**
Content that should be covered
- [ ] This docs should include an overview of engine.json and engine file structure.
- [ ] Developer docs on how to extend Jan. These pages are about what people can build. It should sufficiently outlining the overarching architecture to empower developers to effectively develop upon it.
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

**Additional context**
TBD
