### ISSUE TITLE
docs: update Developer Package Your Extension

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1156]
**Pages**
Package your Engine: https://jan.ai/developer/build-engine/package-your-extension/

**Success Criteria**
Content that should be covered
- [ ] The current endpoint is having error `https://jan.ai/developer/build-extension/package-your-assistant/` needs to change to `https://jan.ai/developer/build-extension/package-your-extension/`
- [ ] This docs should includes packaging, exporting, sharing and publishing your extension.
- [ ] Developer docs on how to extend Jan. These pages are about what people can build. It should sufficiently outlining the overarching architecture to empower developers to effectively develop upon it.
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

**Additional context**
TBD
