### ISSUE TITLE
docs: update Docs Overview 

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1160]
**Pages**
Overall Docs page: https://jan.ai/docs/

**Success Criteria**
Content that should be covered
- [ ] Overall of Docs. Mostly for internal reference and for our core contributors who are building the SDK itself.
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

**Additional context**
Examples, reference pages, resources

**Comment by 0xSage** [comment]
No need for this page. Omit pages that don't really say anything
