### ISSUE TITLE
docs: update Docs Engineering Specs

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1161]
**Pages**
Docs Engineering Specs:  https://jan.ai/docs/engineering/

**Success Criteria**
Content that should be covered
- [ ] Docs Engineering Specs by talking about CoreSDK. Mostly for internal reference and for our core contributors who are building the SDK itself.
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

**Additional context**
Examples, reference pages, resources
