### ISSUE TITLE
docs: update Docs Product Specs

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1162]
**Pages**
Docs Product Specs:  https://jan.ai/docs/product/

**Success Criteria**
Content that should be covered
- [ ] Docs Product Specs. Mostly for internal reference and for our core contributors who are building the SDK itself.
- [ ] Related keywords should be updated.
- [ ] Related images should be compressed.

**Additional context**
Examples, reference pages, resources

**Comment by 0xSage** [comment]
we're moving too fast and specs are already in github. reduce redundancy
