### ISSUE TITLE
feat: CodeNinja-1.0-OpenChat-7b

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1182]
## Objective

- [x] Include [CodeNinja](https://www.reddit.com/r/LocalLLaMA/comments/18pr65c/announcing_codeninja_a_new_open_source_model_good/) in recommended model list
- [ ] Run Human Eval and Benchmarks
- [ ] Share results in the CodeNinja thread 

## Appendix

- https://www.reddit.com/r/LocalLLaMA/comments/18pr65c/announcing_codeninja_a_new_open_source_model_good/
- https://www.reddit.com/r/LocalLLaMA/comments/18pr65c/comment/kepzcnp/?utm_source=share&utm_medium=web2x&context=3

**Comment by hahuyhoang411** [comment]
https://github.com/janhq/jan/pull/1213 Follow this PR for the issue

**Comment by hahuyhoang411** [comment]
Some people did the eval for this model.

```
Python Passed 90 of 91

JavaScript Passed 88 of 91
```
