### ISSUE TITLE
feat: Implement UI page API server

### ISSUE THREAD

**Issue by urmauur** [janhq/jan#1251]
Epic: https://github.com/janhq/jan/issues/773

Figma: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=1200-116269&mode=design&t=wgRfd7ToCgeVX9zI-0

### Tasklist
- [x] Initial / create page API server 
- [x] Update layout and flow API server
- [x] Update hub, setting and thread screen showing tooltip and using disabled button when API server is running

**Comment by imtuyethan** [comment]
Current problem:
![Image](https://github.com/janhq/jan/assets/89722390/a2222233-681c-4448-854a-c19303ab5e25)

Updated design for this cc @urmauur 

![Image](https://github.com/janhq/jan/assets/89722390/5d375a08-8a8a-48b0-b794-4a46539e5bad)

https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=1919-27891&mode=design&t=Qe5o23hWVDQJ0Wev-4

**Comment by Van-QA** [comment]
hi @urmauur, so far the API key textbox is enabled for modification while the server is running :x: 

<img width="1246" alt="image" src="https://github.com/janhq/jan/assets/64197333/4afa4cf9-7698-4b0f-aef6-48ae161c0496">

**Comment by Van-QA** [comment]
The testing will be followed up within this https://github.com/janhq/jan/issues/1697
