### ISSUE TITLE
Epic: Polish Jan UI

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#132]
# Problem
- Jan Web UI does not look polished
- Chat UX is weird
- UX and UI Bugs: 
   - Clicking on LLM shortcuts sometimes creates new chat, sometimes toggles through chat history instead (wtf)
   - Glitchy chat rerendering #84
   - There are a lot of other things that are off and super glitchy

# Success Criteria
- [ ] @drakehere to continuously QA & create `P0`-`P1` issues for UI/UX bugs
- [ ] @drakehere to benchmark with chatGPT and identify **small changes and improvements**, e.g. 
  - Chat history is sorted by dates
  - Left hand pane is collapsible (with animation)
  - Backend reply color difference from the AI
  - Moving cursor as AI replies
  - Copy AI reply button
- [ ] @namchuai to resolve them

# Not in scope
- Fixing the `text to image` templates
