### ISSUE TITLE
epic: Jan Mobile

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#133]
**Objective**
- Jan Mobile should be able to point to a Jan server
    - Cloud.jan.ai
    - Custom Jan Server
- Loads model offerings from Custom Jan Server
- Loads existing conversations from Custom Jan Server

## Org Objectives

- [ ] User can spin up custom Jan server and use on Mobile
- [ ] Jan Server API is well documented

## User Stories
- [x] Users can download Mobile from app store
- User can log into Jan Mobile
    - Chooses server (default: cloud.jan.ai, or enter custom URL)
    - Type in username, password or use OAuth
- User can see models available on that Jan server
- User can see previous conversations on that Jan server
- User can logout

## Requirements

- Jan Server has a standard API
    - /auth (assume every Jan server has its own corresponding Keycloak)

**Comment by louis-jan** [comment]
@dan-jan @hiento09, we should have hasura & llm as component path rather than domain:port. So mobile should just need to input 1 host url.

**Comment by louis-jan** [comment]
cc @namchuai

**Comment by louis-jan** [comment]
There could be 2 options? Jan services could be deployed separately.

**Comment by dan-jan** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFdMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a2719ce63a8e73b7b31fb1704ae2f0a4f0a3a328/image.png)

**Comment by namchuai** [comment]
Work breaking down:
- UI:
    - Create screen after splash screen that user can specify the custom server
    - Has an input to input server address
    - Has a button so that user can try to connect with custom server
    - Has inputs and button for login with email and password
    - In setting, show the current server information
    - Has a button in setting to disconnect with current server
- Features:
    - Ping the custom server's IP address and check if its a Jan compatible server
    - If it's compatible, allow user to sign in / sign up and using the app, backed by the custom server
    - Allow user to disconnect with current server and input a new custom server to connect with

@louis-jan @dan-jan , please let me know your idea. Thank you!

**Comment by louis-jan** [comment]
I think this is quite outdated. Let's put to the icebox? 

Capacitor is the cdd, since it works great with plugin / app architecture and reusable.

**Comment by namchuai** [comment]
Thanks @louis-jan , yeah, let's put in icebox. There's no `jan mobile` any more :(

**Comment by 0xSage** [comment]
Iced
