### ISSUE TITLE
epic: Threads improvement

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1507]
This epic is ongoing and will span multiple sprints, adapting to the team's capacity in each iteration. Our goal is not to complete everything within a single epic. Instead, we will iteratively enhance threads, focusing on the priority of each issue.

## Motivation
To improve current threads feature so solve most of users's pain points & driving to be more chatGPT-like

### In-scope
- [x] Threads should show "Jan using <model_name>" instead of "Assistant #1743 
- [x] Ability to edit messages #1744 
- [ ] Threads should support latex #1211 
- [x] Thread title should be automatically generated based on topics #979 
- [ ] Improve current threads settings with clearer UX for each field #1586 
- [ ] New threads should default to previous threads configurations #1175 
- [ ] Ability to select multiple threads & delete at the same time #1367 
- [x] Show inference time in LLM's reply #1006 
- [x] Put timestamp under thread name in left panel #1472 
- [ ] Search within a thread #1746 
- [ ] Allow users to copy all threads history and share threads #1940
- [ ] Clean threads should clean context & keep thread history #1938 

### Out-of-scope
- **A message progress bar for the taskbar with notification option:** It can be okay for some people to wait minutes for a response, and do other things - and it could be positive for users to be able to choose whether they would like to be notified if the model reaches a set response level: none / first words / half-way / complete
- **Option to limit AI resource allocation to promote overall system useability:** This set of options could be used to allocate maximums in different kinds of system resources for the purpose - so if one wishes to only allocate a maximum of 16GB of normal RAM then that could be done. This complements the previous point. A user may be less interested in a snappy response, so long as they are able to use their system normally.
- **Tool for Jan to assess allocated resources and propose a suitable format of model:** This for 30 second, 3 minute and 15 minute  response times. For ex, 1B 4Q might be suggested as suitable for 30 seconds, while 70B Q4 might be suggested as suitable for 15 minute configuration.

**Comment by imtuyethan** [comment]
Move this to Notion til it is confirmed: https://www.notion.so/jan-ai/Threads-Improvement-2d9fdc3c907645819e76d84c727b7ea1?pvs=4
