### ISSUE TITLE
docs: Restore Docusaurus typography defaults

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1985]
## Todos

- [ ] Reduce Table-of-Contents font-size to Docusaurus default
- [ ] Restore Line Width defaults
- [ ] Restore Line Height defaults
- [ ] Restore List Indentation

### Issue: Table of Contents font size
- Our current ToC font-size: same as body
- Docusaurus: smaller

![image](https://github.com/janhq/jan/assets/101145494/c5dda5dd-49d8-4675-b7c5-d0a7968dc5c3)

### Issue: Line Width
- Our current length for body text: ~140 characters
- Docusaurus: ~120

![image](https://github.com/janhq/jan/assets/101145494/16655ccb-3d78-41ad-a3a8-80be14052a0a)

### Issue: Line Heights
- Our current body text line height: 4 lines
- Docusaurus: 3.1 lines
- Our current typography is difficult to read or scan

![image](https://github.com/janhq/jan/assets/101145494/6767dce9-f035-43c1-bffd-4eba23e5493c)

### Issue: Indentation for Lists
- Our current Indentation: in-line with line start
- Docusaurus: indented, with padding-left

![image](https://github.com/janhq/jan/assets/101145494/33f6bfff-4c52-4c40-8078-71840b26e6ed)
