### ISSUE TITLE
feat: Revamp system monitor & app footer

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#2039]
Related epics: Jan Server #1078 & Observability #1236 
Related design ticket: https://github.com/janhq/jan/issues/1838

_____
# Revamp system monitor
**Problem:** In Jan Server, app displays system informations in the footer bar, which send a lot of requests during app cycle. Should revamp the UI to have expand/collapse section so users can access from anywhere but still ensure the performance.

## Design 
Figma link: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=4427-325119&mode=design&t=LbqHwgt8zLarODK6-4
### Note
- [ ] Remove `system monitor` page & item on the left ribbon
- [ ] Move `system monitor` on the footer
- [ ] Users can only see CPU, mem, GPU metrics when they expand the footer. **Reason:** to reduce the number of requests sent during app cycle in Jan Server.
- [ ] When system monitor is expanded -> update the metrics constantly

#### Users click on `system monitor` to view the metrics:

<img width="638" alt="Screenshot 2024-02-15 at 9 34 38 PM" src="https://github.com/janhq/jan/assets/89722390/264d3851-fde9-4db8-bc3b-b82f446e08c8">

#### System monitor includes running models & activity metrics as below, and users can expand the panel or adjust the size of the panel:

<img width="888" alt="Screenshot 2024-02-15 at 9 34 47 PM" src="https://github.com/janhq/jan/assets/89722390/5ec33457-d470-4046-a072-04f864d4f046">

# Revamp app footer
https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=1-22887&mode=design&t=LbqHwgt8zLarODK6-4
- Remove `my models` -> it's kinda redundant & has no purpose at the moment

<img width="971" alt="Screenshot 2024-02-15 at 9 45 53 PM" src="https://github.com/janhq/jan/assets/89722390/56a11ed1-6ad9-4f78-8421-2a3619099e1b">

**Comment by Van-QA** [comment]
Invisible text in dardmode @urmauur 
![image](https://github.com/janhq/jan/assets/64197333/7096cdf4-4536-4f4e-922d-5c7846a06cab)

**Comment by Van-QA** [comment]
hi @urmauur 
3. menu name is overlapped with System monitor :x:
![image](https://github.com/janhq/jan/assets/64197333/bc464059-f534-425b-8dc6-1fbad5c651cb)

**Comment by Van-QA** [comment]
<img width="532" alt="image" src="https://github.com/janhq/jan/assets/64197333/e6b9670a-acf4-43d3-ab5a-5e1177b14672">
@urmauur please help us correct the UI accordingly, thank you 🙏
