### ISSUE TITLE
epic: Better supports multiple CPU/GPU Hardware optimizations

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2092]
## Motivation
- This is to track the remaining tasks for adding `P2: Nice to have` inference acceleration from https://github.com/janhq/jan/issues/905

## Specs
- 

## Designs
[Figma](link)

## Tasklist
- [ ] https://github.com/janhq/jan/issues/905 - Add more support for Intel iGPU/ eGPU with `sycl`
- [x] https://github.com/janhq/jan/issues/913 - Add more support for AMD rocm
- [ ] https://github.com/janhq/jan/issues/1766 - Add proper support and compatibility for tensorrt-llm on windows/ linux

## Not in Scope
- Adding inference engine abstraction that this issue mentions: https://github.com/janhq/jan/issues/751

**Comment by louis-jan** [comment]
We likely deprioritized #1766, it's already an epic. I think we can close this issue. @hiro-v @Van-QA
