### ISSUE TITLE
milestone: Release 0.4.11

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2627]
#### :truck: Main features:
* Extension should be able to register its own settings #776
* Cloud-api support for Mistral's 3 models #2518
* Rename thread assistant https://github.com/janhq/jan/issues/2510
* Local API server - Support prefix modification for API request URL #2528

#### :test_tube:  Experimental feature: 
* feat: Better support for Japanese/ Chinese keyboard #2585 thank to contributor
* bug: App.log filling hard drive #2485

#### ⏫ Enhancement: 
* MVP - Better error handling for Nvidia driver and CUDA toolkit via settings #2619
* feat: update to use the universal Nitro binary on MacOS target #2068
* chore: Relocate the TensorRT dependency installation action to its settings page #2571

#### ✏️ Notes: + Other bugs fix for Groq, download model, ... and some minor improvements to Jan app 

---

## **2. Regression testing:**
- Build number: [**Jan v0.4.10-371**](https://discord.com/channels/1107178041848909847/1191638499355537418/1227871135937466468) or higher
- Regression test rotation (please help perform the below **checklist**):
  - [x] @Inchoker: [on Windows](https://hackmd.io/fem6VqdeRiKkdNG0YT4fiA?view)
  - [x] @tikikun: [on MacOS Silicon](https://hackmd.io/6hz3DMnkSI2_FRAK9e8rqw?view)
  - [x] @Van-QA quick check on Mac Intel
  - [x] @hiento09 quick check Linux / GPU before the official release

  - Feel free to modify directly to the checklist (add/remove items ...), we will review it after each release.
![image](https://github.com/janhq/jan/assets/64197333/fa1f6c72-c5bd-4065-b7a7-a73b39fb1744)

- :lady_beetle: Any bugs identified during the pre-release, please notify and create a PR from/to main instead of dev to resolve it.
- Standard nightly build will be stopped until Tuesdays :warning:

---

## **3. Documents & Marketing:**
- [x] Rename thread assistant: https://github.com/janhq/jan/issues/2510
- [x] Local API server - Support prefix modification for API request URL #2528
- [x] Extension should be able to register its own settings #776 
- [x] Cloud-api support for Mistral's 3 models #2518
- [x] bug: App.log filling hard drive #2485
- [x] Better error handling for Nvidia driver and CUDA toolkit via settings #2619

#### ✏️ Notes: Please help us link all related documents PR to this ticket, and mark the checklist accordingly to keep track of the progress 🙏

**Comment by Van-QA** [comment]
![image](https://github.com/janhq/jan/assets/64197333/18c85c6c-177e-4b6a-93b5-e71d10c21134)
Hyperlink broke :x: @namchuai

**Comment by irfanpena** [comment]
@Van-QA https://github.com/janhq/docs/pull/111

**Comment by Van-QA** [comment]
Linking to the next release 0.4.12 https://github.com/janhq/jan/issues/2726, thank everyone
