### ISSUE TITLE
milestone: Release v.0.5.0 🍵 Bubur Ayam - WIP

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2904]
#### :truck: Important changes: 
- **Jan app important changes** [Please use this filter for Jan app important changes](https://github.com/janhq/jan/issues?q=milestone%3A"v.0.5.0+🍵%C2%A0Bubur+Ayam"+label%3A"Release+Comms")

#### ‌Depe‌ndency:
<img width="1658" alt="image" src="https://github.com/janhq/jan/assets/64197333/104e3cb3-8764-4117-86bc-263630bc2a7b">

---

## **2. Regression testing:**
- Build number: [**Jan v0.4.14-459**](https://github.com/janhq/jan/actions/runs/9296729054/attempts/2) or higher
- Regression test rotation (please help perform the below **checklist**):
  - [x] @namchuai: [on Windows](https://hackmd.io/fem6VqdeRiKkdNG0YT4fiA?view)
  - [x] @imtuyethan [on MacOS Silicon](https://hackmd.io/6hz3DMnkSI2_FRAK9e8rqw?view)
  - [x] @Van-QA quick check on Mac Intel
  - [x] @hiento09 quick check Linux / GPU before the official release

  - Feel free to modify directly to the checklist (add/remove items ...), we will review it after each release.
<img width="675" alt="image" src="https://github.com/janhq/jan/assets/64197333/769415a7-2379-4ed3-8941-2b24454ee9fe">

- :lady_beetle: Any bugs identified during the pre-release, please notify and create a PR from/to main instead of dev to resolve it.
- Standard nightly build will be stopped temporally :warning:

## **3. Documents & Marketing:**
- [ ] ‌UI changed, need review / update on all ‌imag‌es in our docs

#### ✏️ Notes: Please help us link all related documents PR to this ticket, and mark the checklist accordingly to keep track of the progress 🙏
