### ISSUE TITLE
epic: Jan can See in Experimental

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#294]
# Objectives
- Allow users to insert images and generate responses using the LLaVa model.
- Enhance user experience by providing a seamless interface for image insertion and prompt creation.

## Leads

- Product: @imtuyethan 
- Engineering: @vuonghoainam @louis-jan @urmauur @tikikun 

## User Stories
_In Scope_

1. **As a user, I want to easily insert images into Jan's interface, either by dropping files or using buttons:**

    - *Scenario:* I aim to effortlessly insert images.
    - *Acceptance Criteria:* The interface should support drag-and-drop functionality or provide clear buttons for uploading images.

2. **As a user, I want a user-friendly interface to create text prompts for the LLaVa model linked to the inserted images:**

    - *Scenario:* I seek a seamless way to input prompts for the LLaVa model connected to the inserted images.
    - *Acceptance Criteria:* The interface should offer a clear space to input text prompts directly related to the inserted images.

3. **As a user, I want to view and interact with LLaVa model responses based on the inserted images and associated prompts:**

    - *Scenario:* After inserting images and prompts, I expect to access and interact with the LLaVa model's generated responses.
    - *Acceptance Criteria:* The generated responses should be visible and easily accessible within the interface, showcasing accurate output based on the inserted image and associated prompts.

_Out-of-Scope_
- As a user, I want to see prompts suggestions based on the capabilities of the LLaVa model.
- As a user, I want to attach many images at the same time.

## Design Wireframes

**Key Considerations**

[Figma link
](https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=783-43738&mode=design&t=cRokDaaZm5mgnx3H-4)

![Image](https://github.com/janhq/jan/assets/89722390/94d2f74d-cf54-47c4-9c20-ec74a268caaf)

## Engineering & Architecture

_In Scope_
- For @vuonghoainam to input.
- Nitro supports image capability @tikikun 

_Out-of-Scope_

## Tasklist
- [x] https://github.com/janhq/jan/pull/2069
- [x] https://github.com/janhq/jan/issues/1049
- [x] https://github.com/janhq/jan/issues/1088
- [x] https://github.com/orgs/janhq/projects/5/views/26?pane=issue&itemId=47514666

# Resources
https://twitter.com/nathanlands/status/1709539003312259172?s=46&t=osxIAvq8ztXuDbNAm11thA
https://twitter.com/LMStudioAI/status/1734640355318944190

# Out of scope
[Nitro supports speech/hear capability](https://github.com/orgs/janhq/projects/5/views/7?filterQuery=milestone%3A%22Jan+can+See%22&pane=issue&itemId=40875073)

**Comment by imtuyethan** [comment]
# Objectives
- Allow users to insert images and generate responses using the LLaVa model.
- Enhance user experience by providing a seamless interface for image insertion and prompt creation.


# Success Metrics
As Jan does not do any invasive tracking of user activities, the only way we can measure the adoption of the feature is through local image model downloads:
- Monitor and track the number of downloads specifically for models that support image reading within Jan Hub or Jan's open-source repository.
- Initial target: 50% of current active users within the first three months after its release.


# Milestones

# Requirements

| Capability  | User story | 
| ------------- | ------------- |
| Image Insertion | As a user, I want to insert images easily into Jan's interface, either by dropping files into the app or through buttons. |
| Prompt Creation | As a user, I want a clear interface to create text prompts for the LLaVa model to read the inserted images. |
| Response Display | As a user, I want to see the responses generated by the LLaVa model based on the inserted image and prompts. |
| Prompts (Optional) | As a user, I want the input box for prompts to be conditionally rendered based on the availability of the LLaVa model. |

#### Technical Implementation
- For @vuonghoainam to input.
- Nitro supports image capability @tikikun 

# Related tasks
- Design: [Jan can see](https://github.com/orgs/janhq/projects/5/views/7?pane=issue&itemId=47514666)
- Tech:
  * Updated model.json for multiple model artifact](https://github.com/janhq/jan/issues/1049)
  * 

# Ref
https://twitter.com/nathanlands/status/1709539003312259172?s=46&t=osxIAvq8ztXuDbNAm11thA
https://twitter.com/LMStudioAI/status/1734640355318944190

# Out of scope
[Nitro supports speech/hear capability](https://github.com/orgs/janhq/projects/5/views/7?filterQuery=milestone%3A%22Jan+can+See%22&pane=issue&itemId=40875073)

**Comment by imtuyethan** [comment]
**Motivation**
- 

**Specs & Designs**
- 

**In Scope**
- 

**Not in Scope**
- 

**Tasklist**
> Note: All issues need to share the same `milestone` as this epic
- 

**Related Milestones**
- Past
- Future

**Comment by 0xSage** [comment]
Can this be turned on for nightly/experimental? IF we have it then can we use it?

**Comment by 0xSage** [comment]
Goal: turn it on for experimental/nightly

**Comment by Van-QA** [comment]
Tested and looking good on Jan 0.4.7-304 ✅
