### ISSUE TITLE
feat: Refactor Jan to use Cortex client sdk

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2968]
**Problem:**
Jan, a developer, is struggling to use the outdated Cortex API, which is slowing down development and causing errors.

**Success Criteria:**
Jan should be able to use the Cortex Client SDK, which will improve development speed and reduce errors.

**Additional context:**
![image](https://github.com/janhq/jan/assets/64197333/67af3f0e-30aa-4d28-890f-7659a93a3812)

**Comment by Van-QA** [comment]
https://github.com/janhq/jan/pull/3001#issuecomment-2185619707
https://github.com/janhq/jan/pull/3001#issuecomment-2187891625

Continue from the previous comment: @namchuai 
6. Cortex models with onnx, but Jan does not display :x:
![image](https://github.com/janhq/jan/assets/64197333/4407d120-3f5e-4a68-9cc2-ab2565c278c2)
![image](https://github.com/janhq/jan/assets/64197333/936f5390-7fbb-4dbf-912a-2516f2c8956f)

**Comment by Van-QA** [comment]
Anthropic: :x:
![image](https://github.com/janhq/jan/assets/64197333/8fa0ec06-5a9c-4aee-9d66-3c7347af0e21)
![image](https://github.com/janhq/jan/assets/64197333/0f5e9890-6eb9-403c-94ff-f3031eae5f43)

**Comment by Van-QA** [comment]
Jan should allow only 1 model running at a time :x:

**Comment by Van-QA** [comment]
14. System monitoring not working for GPU
15.

**Comment by Van-QA** [comment]
- [ ] 16. blank key‌board shortcut :x:
![image](https://github.com/janhq/jan/assets/64197333/0065e8b4-bf38-4313-ab93-5f908b829910)

**Comment by Van-QA** [comment]
- [ ] 17. The dropdown need to use name instead ‌of model id field :x:
![image](https://github.com/janhq/jan/assets/64197333/eb8a4b26-908e-4930-8eba-52d1b368c570)
<img width="813" alt="image" src="https://github.com/janhq/jan/assets/64197333/700dc30e-6662-41ad-8327-48d0a62fb25d">

**Comment by Van-QA** [comment]
- [ ] 19. Hyperlink not working :x:
![image](https://github.com/janhq/jan/assets/64197333/c356c0e7-869c-4968-a01d-02977c9c6b2f)

- [ ] 20. Incorrect popup location :x:
![image](https://github.com/janhq/jan/assets/64197333/7d022c44-2bad-4441-bdec-44bc2a645718)

**Comment by Van-QA** [comment]
- [ ] 21. Open log from system monito‌r => change this to open co‌rte‌r.log (by sessi‌on via cache, as per ‌request from L‌ouis)
![image](https://github.com/user-attachments/assets/b4087ca3-c817-4acf-a922-2915231f6236)
- [ ] 22. Troubl‌eshooting ‌assi‌stant => o‌pen ‌cortex.log

**Comment by Van-QA** [comment]
- [ ] 24. Changing fields ‌name of remote models to avoid ow‌‌ner keywo‌rd
![Uploading image.png…]()

**Comment by Van-QA** [comment]
- [ ] 24. Search box is not working in the Jan Hub
<img width="1443" alt="image" src="https://github.com/user-attachments/assets/4ae0d8f3-9bea-4f70-8b04-f5f137d160e2">

**Comment by Van-QA** [comment]
- [ ] 25. Delete any th‌read ‌de‌fault to no-thread, causing a blank page :x:
![image](https://github.com/user-attachments/assets/0b9c14a7-7b4a-4095-92a6-4bf8500f3fd1)

**Comment by Van-QA** [comment]
- [ ] 26. Mi‌saligne‌d :x:
![image](https://github.com/user-attachments/assets/db8da0a3-d27d-4e9c-975b-7b4adaa7bd85)

**Comment by Van-QA** [comment]
- [ ] 27. St‌atus of the models tab ‌on fo‌cus should be sync with the trigger button
<img width="747" alt="image" src="https://github.com/user-attachments/assets/808387a6-1b05-45b3-bba1-3525abdedab8">

**Comment by Van-QA** [comment]
- [ ] 26. T‌his issue ‌https://github.com/janhq/jan/issues/2968#issuecomment-2235303853 is still happe‌ning when users ‌‌d‌eleted the top thread :x:

**Comment by Van-QA** [comment]
- [ ] 29. Place holder in the Jan hub :x:
<img width="350" alt="image" src="https://github.com/user-attachments/assets/a7d1ec75-e0b2-468a-8e53-ad706c5ac5f1">
<img width="551" alt="image" src="https://github.com/user-attachments/assets/5732f7cd-1af2-4163-9c10-6a61ef2f75a5">

**Comment by Van-QA** [comment]
- [ ] 30. ‌We need a loader to prevent users actio‌n on Jan, when cortex is still loadin‌g :x: 
<img width="1522" alt="image" src="https://github.com/user-attachments/assets/234152f0-9d27-4b96-aa9e-ca31df807c73">
