### ISSUE TITLE
epic: Jan has Stable, Beta and Nightly versions

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2985]
**Problem:**
Users want to run and test both the stable and nightly versions of the app simultaneously, but so far Jan can only have one instance of the app running at a time.

**Success Criteria:**
Users would like the Jan app to have the capability to install and run multiple instances of the app, allowing me to have both the stable and nightly versions running simultaneously. This would enable users to easily compare and test new features while still having access to the stable version.

**Additional Context:**
This feature request is important for users who want to stay up-to-date with the latest features and improvements, while still having to a stable version of the app. It would also be helpful for users who need to test and validate new features before they are released to the stable version.

**Acceptance criteria**
- [ ] Handle different Jan data folder for nightly
- [ ] Port number 
- [ ] CI update to cover app bundle

**Task**

- [x] New CI for beta version
- [ ] Modify Nightly version to use different folder and port

**Comment by imtuyethan** [comment]
Note from @hiento09 

Current flow: Continuously push code to the dev branch => build Nightly => when ready for release => merge dev into main => tag Stable.
Flow with beta: Any release must have a clear release plan from the start => push code to the dev branch according to the plan with feature and bug tickets => release a beta version with the planned features and bug fixes, and notify users => keep the beta for one-two week. During this time, if any bugs are reported by users or any issues arise, hotfix the beta version to main (the dev branch team continues development as usual) => After that, officially tag Stable."

Refer to cortex release strategy here https://github.com/janhq/cortex.cpp/discussions/1174
