### ISSUE TITLE
milestone: Release v.0.5.2 - WIP

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2999]
#### :truck: Important changes: 
- **Jan app important changes** [Please use this filter for Jan app important changes](https://github.com/janhq/jan/milestone/58)

#### ‌Depe‌ndency:
![image](https://github.com/janhq/jan/assets/64197333/3f81fcbf-0a93-4b1d-b9ac-76c71f84ec12)

---

## **2. Regression testing:**
- Build number: [**Jan v0.5.1-522**](https://discord.com/channels/1107178041848909847/1191638499355537418/1260888429957353482) or higher
- Regression test rotation (please help perform the below **checklist**):
  - [ ] @gabrielle-ong : [on Windows](https://hackmd.io/fem6VqdeRiKkdNG0YT4fiA?view)
  - [ ] @marknguyen1302 : [on MacOS Silicon](https://hackmd.io/6hz3DMnkSI2_FRAK9e8rqw?view)
  - [ ] @Van-QA quick check on Mac Intel
  - [ ] @hiento09 quick check Linux / GPU before the official release

  - Feel free to modify directly to the checklist (add/remove items ...), we will review it after each release.
![image](https://github.com/janhq/jan/assets/64197333/265cdef7-f030-4efc-a39a-a0d622f92fb0)

- :lady_beetle: Any bugs identified during the pre-release, please notify and create a PR from/to main instead of dev to resolve it.
- Standard nightly build will be stopped temporally :warning:

## **3. Documents & Marketing:**
- [ ] ‌https://github.com/janhq/jan/issues/2872
- [ ] Wiping extensions folder guideline
#### ✏️ Notes: Please help us link all related documents PR to this ticket, and mark the checklist accordingly to keep track of the progress 🙏

**Comment by 0xSage** [comment]
Thank. you for this. Really thorough
