### ISSUE TITLE
feat: Remote APIs can fetch Model List

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3374]
## Goal 

- Remote API Extensions can fetch an updated model list (e.g. params that can be passed in)
- Users can select model from list, once 
- Users should only see major models (i.e. not nightly) 
- We will not need `model.yaml` for each remote model
- [Stretch] Users can add additional model names in the Remote API's Settings page (e.g. nightly)

## Tasklist

- [ ] #3452 
- [x] #3157 
- [ ] #3392 
- [ ] https://github.com/janhq/jan/issues/3452
- [ ] https://github.com/janhq/jan/issues/3194
- [ ] https://github.com/janhq/jan/issues/3370

## Archive

Fetch list of remote models per engine via API => No need to add model json for each remote model

Remote engines: reuse from Jan with a few modifications for more remote models (mentioned abo‌ve) -> Hash user api key - raw content - remove -> files still there

**Comment by louis-jan** [comment]
Strict tests on model fetching are required for the update, e.g., sometimes the service could be down during the build and the app bundles an empty list of models.

Possible situation: 
- App passed during manual tests / dev
- Request failed during bundle for release (tag trigger)

Suggestion: 
- Publish = Bundle -> Test -> Distribute

**Comment by dan-homebrew** [comment]
I am merging this issue into #3505
