### ISSUE TITLE
milestone: Release v.0.5.3

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3454]
#### :truck: Important changes: 
- **Jan app important changes** [Please use this filter for Jan app important changes](https://github.com/janhq/jan/milestone/60)

#### ‌Depe‌ndency:
TBU

---

## **2. Regression testing:**
- Build number: [**Jan v0.5.2-617**] or higher
- Regression test rotation (please help perform the below **checklist**):
  - [ ] : [on Windows](https://hackmd.io/fem6VqdeRiKkdNG0YT4fiA?view)
  - [ ] : [on MacOS Silicon](https://hackmd.io/6hz3DMnkSI2_FRAK9e8rqw?view)
  - [ ] quick check on Mac Intel
  - [ ]  quick check Linux / GPU before the official release

  - Feel free to modify directly to the checklist (add/remove items ...), we will review it after each release.

- :lady_beetle: Any bugs identified during the pre-release, please notify and create a PR from/to main instead of dev to resolve it.
- Standard nightly build will be stopped temporally :warning:

## **3. Documents & Marketing:**
- [x] ‌Jan default data folder changed https://github.com/janhq/jan/pull/3443
#### ✏️ Notes: Please help us link all related documents PR to this ticket, and mark the checklist accordingly to keep track of the progress 🙏

**Comment by Van-QA** [comment]
Jan 0.5.3 is released to stable version of Jan app: https://github.com/janhq/jan/releases/tag/v0.5.3
