### ISSUE TITLE
chore: Jan.ai Homepage

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#350]
## Objective

- Clean and easy-to-understand Homepage
- "Features" section with screenshots on cards
- Should look good on mobile

## Tasks

- [ ] Banner needs to direct user to latest release (vs. "Under Construction")
- [ ] Feature section should use Tailwind Cards
    - [ ] https://tailwindui.com/components/ecommerce/components/product-lists#component-ce3346a7007ed3114735fd9771b3d393
- [ ] Gleap integration

### Broken Dark Mode toggle 

- Toggling Dark Mode sometimes results in images/colors not updating

<img width="1200" alt="image" src="https://github.com/janhq/jan/assets/101145494/19fd713e-4bac-4c4f-b993-9513ce77c601">

**Comment by dan-jan** [comment]
## "Chat Screen"

![image](https://github.com/janhq/jan/assets/101145494/4d5a3c28-8772-434c-bf6b-d0813df2b1ab)

## "Create a Bot"

## Manage Model Parameters

<img width="740" alt="image" src="https://github.com/janhq/jan/assets/101145494/c527dc09-886e-459e-8c0c-7ade24ba693f">

## 1-click Model Installation

![image](https://github.com/janhq/jan/assets/101145494/56b4dcba-2550-4af7-9630-9fe4cdb17db8)

## Running Models

<img width="1012" alt="image" src="https://github.com/janhq/jan/assets/101145494/0feaabb5-78ad-431c-886b-133973e63f45">

## System Monitor

Monitor RAM, etc

<img width="331" alt="image" src="https://github.com/janhq/jan/assets/101145494/57185609-63d8-4f69-bd14-de279f253fa5">

## Plugin Architecture

<img width="822" alt="image" src="https://github.com/janhq/jan/assets/101145494/1be88ec5-f9a0-4f66-86fb-328080a142d8">

## Settings

<img width="854" alt="image" src="https://github.com/janhq/jan/assets/101145494/fc128d13-d99c-40f4-88a1-4963ff84ade2">
