### ISSUE TITLE
feat: Add support for AMD GPUs 

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3529]
### #

- [X] I have searched the existing issues

### Background

Currently, Jan only supports NVIDIA GPUs for acceleration. Users with AMD GPUs, particularly those using eGPUs on Intel Macs, are unable to utilize their graphics hardware for acceleration in Jan. This limits the performance potential for a segment of Jan users who have invested in AMD GPU solutions.

### Feature request

- [ ] https://github.com/janhq/jan/issues/2676
- [ ] https://github.com/janhq/jan/issues/2587
- [ ] https://github.com/janhq/jan/issues/3394
- [ ] AMD GFX support on Intel Mac https://discord.com/channels/1107178041848909847/1269379375451603084
- [ ] https://github.com/janhq/docs/issues/15
- [ ] to be updated

### Proposed Implementation

-

### Additional Notes

Consider prioritizing support for popular AMD GPU models like the Vega series initially.

**Comment by cracksauce** [comment]
Commenting in support of this feature request

**Comment by alsyundawy** [comment]
please support gpu amd discreet on macbook pro 2017-2019

**Comment by camilocorreao** [comment]
Not able to use Jan with amd GPUs on Linux? Sad...

**Comment by syorito-hatsuki** [comment]
> Not able to use Jan with amd GPUs on Linux? Sad...

You can try over Vulkan, but it's still was slow. R7 2700 faster that RX6600 over Vulkan (Using Qwen 2.5 32B Q4 model)

**Comment by watermel0l** [comment]
AMD support is a great idea.

**Comment by 32bitx64bit** [comment]
Hopefully ROCM support can be supported. But those who don't know, you can enabled the admittedly slower Vulkan support.

Go into settings - > Advanced settings and enable "experimental mode"
Then ensure that linux-amd64-vulkan is selected under the Local engine settings tab, if not just select it.
And you should be running with GPU acceleration, though in my testing (I used LM Studio for ROCM on linux) it seems that the Vulkan version is slightly slower than ROCM. So it'd be nice for ROCM to actually be officially supported in Jan.

Anyways hope this helps :)
