### ISSUE TITLE
epic: Fix Local Engine issues (llama.cpp)

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/jan#3614]
## Goal 

- Fix Local Engine issues
- Focus on llama.cpp first

### Out-of-scope

- Other engines: TensorRT-LLM, ONNX

## Tasklist

Our issues boil down to 5-6 main cortex issues

### Architecture

- [ ] Document Jan -> Cortex integration and communication method (e.g. in Architecture Spec)
- [ ] Rename extension? (semantic naming)

### Major Cortex Issues
- [x] https://github.com/janhq/cortex.cpp/issues/1077
- [x] https://github.com/janhq/cortex.cpp/issues/1076
    - [x] https://github.com/janhq/jan/issues/3361
- [x] https://github.com/janhq/cortex.cpp/issues/1072
- [ ] https://github.com/janhq/cortex.cpp/issues/1151
    - [ ] https://github.com/janhq/jan/issues/2320
- [x] https://github.com/janhq/cortex.cpp/issues/1154
- [x] https://github.com/janhq/models/issues/22

**Comment by 0xSage** [comment]
Outdated. And closing as it is a dupe of #3825
