### ISSUE TITLE
QA: Jan 0.5.4 Release Sign-off

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/jan#3682]
# Windows Regression test

**Release Version:** v0.5.4

**Operating System:** Windows

---

### 1. Users install app (New user flow)

- [x] :rocket: Installation package is not corrupted and passes all security checks.
- [x] :key: App launches successfully after installation.

### 2. Users update app (Existing user flow)

- [x] :key: Validate that the update does not corrupt user data or settings.
- [x] :key: App restarts or prompts the user to restart after an update.
- [x] When updating the app, check if the `/models` directory has any JSON/YML files that change according to the update.
- [x] Updating the app also updates extensions correctly, test functionality changes.

### 3. Users uninstall / close app

- [x] :key: After closing the app, all models are unloaded.
- [ ] :key::warning: Uninstallation process removes the app successfully from the system.
- [ ] Clean the data folder and open the app to check if it creates all the necessary folders, especially models and extensions.

### 1. Shortcut key

- [x] :key: Test each shortcut key to confirm it works as described (My models, navigating, opening, closing, etc.).

### 2. Users check the `active model`

- [x] :key: The app correctly displays the state of the loading model (e.g., loading, ready, error).
- [x] :key: Confirm that the app allows users to switch between models if multiple are available.
- [ ] Check that the app provides feedback or instructions if the model fails to load.
- [ ] Verify the troubleshooting assistant correctly capture hardware / log info [#1784](https://github.com/janhq/jan/issues/1784)

### 1. Users can chat with Jan, the default assistant

- [x] :key: Sending a message enables users to receive responses from model.
- [x] :key: Conversation thread is maintained without any loss of data upon sending multiple messages.
- [x] ‌Users should be able to edit msg and the assistant will re-generate the answer based on the edited version of the message.
- [x] Test for the ability to send different types of messages (e.g., text, emojis, code blocks).
- [x] Check the output format of the AI (code blocks, JSON, markdown, ...).
- [x] :key: Validate the scroll functionality in the chat window for lengthy conversations.
- [x] User can copy / delete the response.
- [x] :key: Check the `clear message` / `delete entire chat` button works.
- [x] Deleting all the chat retains the model instruction and settings.
- [ ] :key: Appropriate error handling and messaging if the assistant fails to respond.
- [x] Test assistant's ability to maintain context over multiple exchanges.
- [x] :key: Check the `create new chat` button, and new conversation will have an automatically generated thread title based on users msg.
- [x] Changing `models` mid-thread the app can still handle it.
- [x] Check the `regenerate` button renews the response (single / multiple times).
- [x] Check the `Instructions` update correctly after the user updates it midway (mid-thread).

### 2. Users can customize chat settings like model parameters via both the GUI & model.yml

- [x] Adjust model parameters (e.g., Temperature, Top K, Top P) from the GUI and verify they are reflected in the chat behavior.
- [x] :key: Changes can be saved and persisted between sessions.
- [ ] Users can access and modify the model.yml file.
- [ ] :key: Changes made in model.yml are correctly applied to the chat session upon reload or restart.
- [x] Check the maximum and minimum limits of the adjustable parameters and how they affect the assistant's responses.
- [x] :key: Users switch between threads with different models, the app can handle it.

### 3. Model dropdown
- :key: Model list should highlight recommended based on user RAM (this is not really correct, I think it's based on static formula)
- [x] Model size should display (for both installed and imported models)

### 4. Users can click on a history thread
- [x] Chat window displays the entire conversation from the selected history thread without any missing messages.
- [x] Historical threads reflect the exact state of the chat at that time, including settings.
- [x] :key: Ability to delete or clean old threads.
- [x] Changing the title of the thread updates correctly.

### 5. Users can config instructions for the assistant.
- [x] Instructions set by the user are being followed by the assistant in subsequent conversations.
- [x] :key: Changes to instructions are updated in real time and do not require a restart of the application or session.
- [x] :key: Ability to reset instructions to default or clear them completely.
- [ ] :key: RAG - Users can import documents and the system should process queries about the uploaded file, providing accurate and appropriate responses in the conversation thread.
- [ ] :key: Jan can see - Users can import image and Model with vision can generate responses (e.g. LLaVa model). [#294](https://github.com/janhq/jan/issues/294)

### 1. Users can discover recommended models
- :key: Each model's recommendations are consistent with the user’s activity and preferences.
- [x] Search models and verify results / action on the results

### 2. Users can download models suitable for their devices, e.g. compatible with their RAM

- [x] Model list should be in order: Featured > Remote > Local
- [x] :key: Ensure that models are labeled with RAM requirements.
- [x] :key: Check the download model functionality and validate if the cancel download feature works correctly.

### 3. Users can download models via a HuggingFace URL [#1740](https://github.com/janhq/jan/issues/1740)

- [x] :key: Import via Hugging Face Id / full HuggingFace URL, check the progress bar reflects the download process
- [x] :key: Test deeplink import [#2876](https://github.com/janhq/jan/issues/2876)
- [ ] :key: Users can use / remove the imported model.

### 4. Users can import new models to the Hub

- [x] :key: Ensure import successfully via drag / drop or upload GGUF.
- [x] :key: Verify Move model binary file / Keep Original Files & Symlink option are working
- [x] Users can add more info to the imported model / edit name
- [x] :key: Ensure the new model updates after restarting the app.

### 5. Users can use the model as they want

- [x] :key: Check `start` / `stop` / `delete`  button response exactly what it does.
- [x] Check if starting another model stops the other model entirely.
- [x] :rocket: Navigate to `hub` > Click `Use` button to use model. Expect to jump to thread and see the model in dropdown model selector. 
- [x] :key: Check when deleting a model it will delete all the files on the user's computer.
- [x] :warning:The recommended tags should present right for the user's hardware.

### 6. Users can Integrate With a Remote Server
- [ ] :key: Import openAI GPT model https://jan.ai/guides/using-models/integrate-with-remote-server/ and the model displayed in Hub / Thread dropdown
- [ ] Users can use the remote model properly (openAI GPT, Groq)

### 1. Users can see disk and RAM utilization

- [x] :key: Verify that the RAM and VRAM utilization graphs  accurately reported in real time.
- [x] :key: Validate that the utilization percentages reflect the actual usage compared to the system's total available resources.
- [ ] :key: Ensure that the system monitors updates dynamically as the models run and stop.

### 2. Users can start and stop models based on system health

- [x] :key: Verify the `Start/Stop` action for a model, the system resource usage reflects this change.
- [x] Confirm that any changes in model status (start/stop) are logged or reported to the user for transparency.
- [x] :key: Check the functionality of `App log` to ensure it opens the correct folder in the system file explorer.

### 1. Appearance

- [x] :key: Test the `Light`, `Dark`, and `System` theme settings to ensure they are functioning as expected.
- [x] Confirm that the application saves the theme preference and persists it across sessions.
- [x] Validate that all elements of the UI are compatible with the theme changes and maintain legibility and contrast.
- [x] Desktop app should have shadow

### 2. Extensions [TBU]

- Validate the `Install Extensions` process by selecting and installing a plugin file.
- [ ] Enable / disable extensions and the UI should reflex accordingly

### 3. Extension group

- [ ] :key: Users can set valid Endpoint and API Key to use remote models
- [x] Monitoring extension should allow users to enable / disable log and set log Cleaning Interval

### 4. Advanced settings

- [x] :key: Test the `Experimental Mode` toggle to confirm it enables or disables experimental features as intended.
- [x] :key: Check the functionality of `Open App Directory` to ensure it opens the correct folder in the system file explorer.
- [x] Users can move **Jan data folder**
- [x] Validate that changes in advanced settings are applied immediately or provide appropriate instructions if a restart is needed.
- [ ] Attemp to test downloading model from hub using **HTTP Proxy** [guideline](https://github.com/janhq/jan/pull/1562)
- [ ] Logs that are older than 7 days or exceed 1MB in size will be automatically cleared upon starting the application.
- [ ] Users can click on Reset button to **factory reset** app settings to its original state & delete all usage data.
    - [ ] Keep the current app data location
    - [ ] Reset the current app data location
- [x] Users can enable the setting and chat using quick ask.

### 5. Engine
- [ ] :key: TensorRT Engine - Users able to chat with the model
- [ ] :key: Onnx Engine - Users able to chat with the model
- [ ] :key: Other remote Engine - Users able to chat with the model

### 6. My models:
- [x] :key: List downloaded models (on devices) with correct size / status
- [ ] :key: Import from Hugging Face with restricted repository (via access token)
- [x] Can start / stop models delete models

### 1. Local Server Usage with Server Options
- [ ] :key: Explore API Reference: Swagger API for sending/receiving requests
    - [x] Use default server option
    - [ ] Configure and use custom server options
- [x] Test starting/stopping the local API server with different Model/Model settings
- [x] Server logs captured with correct Server Options provided
- [x] Verify functionality of Open logs/Clear feature
- [x] Ensure that threads and other functions impacting the model are disabled while the local server is running

**Comment by dan-homebrew** [comment]
@urmauur Weird bug: 0.5.3-638 does not have shadow on my Windows machine. 

![Image](https://github.com/user-attachments/assets/ff11a24a-0a03-4078-af87-897ea07cb63f)

However, the shadow and border showed up in 0.5.3-629 just a few days ago:

https://github.com/janhq/jan/issues/3628#issuecomment-2345745074

**Comment by dan-homebrew** [comment]
We should consider changing the UX for the "Updating" screen, to avoid blanking out the full App display (e.g. if something goes wrong)

![Image](https://github.com/user-attachments/assets/c616f59b-fed9-4bfa-8634-d80095c6d8cd)

**Comment by dan-homebrew** [comment]
To add to QA Checklist:
- Input in non-English language (e.g. Chinese)
- Test for Border in Appearance

**Comment by dan-homebrew** [comment]
Poorly worded checklist item, needs to be more specific: "Updating the app also updates extensions correctly, test functionality changes."

**Comment by dan-homebrew** [comment]
QA test needs better fidelity: 
Check that the app provides feedback or instructions if the model fails to load.

- Need clear instructions to create conditions for failed model
- Need clear instructions for what to look for on failed model load

**Comment by dan-homebrew** [comment]
Might be good idea to include prompts for how to get model to generate JSON, code, etc: 

Check the output format of the AI (code blocks, JSON, markdown, ...).

**Comment by dan-homebrew** [comment]
Product: We should have a less aggressive blur on modals

![image](https://github.com/user-attachments/assets/da1fb112-ff9f-4b9e-972e-fb2dd53db87e)

**Comment by dan-homebrew** [comment]
QA test needs more details: 

Appropriate error handling and messaging if the assistant fails to respond.

**Comment by dan-homebrew** [comment]
Product: Prompt Template should have larger box (already addressed in upcoming epic)
![image](https://github.com/user-attachments/assets/739f0d5c-59ac-4014-b10b-2e33c790da30)

**Comment by dan-homebrew** [comment]
Product: Max Tokens is constrained by Context Length in Engine Settings, which might not be visible to user if Engine is closed

![image](https://github.com/user-attachments/assets/4af2bc2d-a33c-451a-8002-3a89355e065b)

**Comment by dan-homebrew** [comment]
Product: User should be able to increase Max Tokens to max Engine's Context Length, rather than hidden param that constrains it

![image](https://github.com/user-attachments/assets/7f75f7ca-b03d-48a5-9663-a3f9c04a11d4)

**Comment by dan-homebrew** [comment]
Product: there's no way for me to open the `model.yaml` for a Model?

![image](https://github.com/user-attachments/assets/cfe52fa0-c4ac-4b6c-bda7-dbbd9c2f22c0)

![image](https://github.com/user-attachments/assets/3dc14ca5-690b-47e8-8349-920b2fd9257a)

**Comment by dan-homebrew** [comment]
Bug found: 

- Download on Hub
- Navigate to another page
- Navigate back to Hub
- Hub then shows "Use", even though Model is still downloading

![image](https://github.com/user-attachments/assets/83767471-35c1-47e8-a3ea-a5a92eb5a0b4)

![image](https://github.com/user-attachments/assets/a117f1c8-9d32-43fa-8842-1cdbf884d640)

**Comment by dan-homebrew** [comment]
How are we testing this? 

🔑 Onnx Engine - Users able to chat with the model

**Comment by dan-homebrew** [comment]
Product: Import Folder should be more like "Link Folder", and in a different part of Jan
![image](https://github.com/user-attachments/assets/4aa1da88-41f6-4564-9cb3-8256fa79b4a4)

**Comment by dan-homebrew** [comment]
Product: Importing Model does not show any status (when does the model import complete?)
![image](https://github.com/user-attachments/assets/a719ad0c-2398-450b-a1be-2ea3d22eb45c)

**Comment by dan-homebrew** [comment]
Baklava failed to start, should be removed from Model List
![image](https://github.com/user-attachments/assets/158c4072-f5d2-44bf-9016-01031f656e1c)

**Comment by dan-homebrew** [comment]
Product: System Monitor should not cover input box (user should be able to run System Monitor concurrently while using app)
![image](https://github.com/user-attachments/assets/17d2ba4b-e195-47fc-bf3f-a4105b54aefa)

**Comment by dan-homebrew** [comment]
QA: Moving Jan Data Folder needs to be tested
![image](https://github.com/user-attachments/assets/1dba0088-888a-4664-a6f5-0a717f735792)

**Comment by dan-homebrew** [comment]
Product: Moving Jan data folder should show some progress meter, otherwise it's very scary for the user. 

![image](https://github.com/user-attachments/assets/67d92561-86a8-4a8c-ae75-ef597a1848a6)
![image](https://github.com/user-attachments/assets/3f994447-6edb-4abc-b751-51c7ab9e046e)

**Comment by dan-homebrew** [comment]
UI Nitpick: GPU textbox is smaller than GPU name
![image](https://github.com/user-attachments/assets/ae09b444-e5bc-4571-97db-d88ceb2b0d51)

**Comment by dan-homebrew** [comment]
Quick Ask does not have shadow
![image](https://github.com/user-attachments/assets/fa3292be-f907-41ab-bf8e-0cfb31fc89d8)

**Comment by dan-homebrew** [comment]
Bug: Failed to start Server 
![image](https://github.com/user-attachments/assets/4fc24ab3-081e-4ed2-9a61-e6bda78f2dff)

**Comment by dan-homebrew** [comment]
Bug: Failed to start Server 
![image](https://github.com/user-attachments/assets/4fc24ab3-081e-4ed2-9a61-e6bda78f2dff)

[app.log](https://github.com/user-attachments/files/17025483/app.log)

**Comment by dan-homebrew** [comment]
Product: API Server (or Jan) should deal with port conflicts gracefully:

- Pick different port number
- Prompt the user to pick a different port number

![image](https://github.com/user-attachments/assets/4eb0b700-82e4-471f-94ce-7af0e6a31ff1)

**Comment by dan-homebrew** [comment]
Product: Server Logs should be more useful, and be collapsible so user can expand them if needed

**Comment by dan-homebrew** [comment]
Product: `ngl` parameter is not showing correct num of max layers? 

- Can this be inferred from the GGUF file?

**Comment by dan-homebrew** [comment]
Product: Jan logs are not very informative

**Comment by dan-homebrew** [comment]
Product: Nitpick, Jan's local API reference should be collapsed to give user full picture of what all methods are available
![image](https://github.com/user-attachments/assets/d8452624-99b8-471d-94b0-e94ff51a04f0)

**Comment by dan-homebrew** [comment]
Product: TensorRT-LLM and Local Models should be at the top
![image](https://github.com/user-attachments/assets/e2db014d-aec6-46b9-b6ab-c7d1b389fada)

**Comment by dan-homebrew** [comment]
Bug: TensorRT-LLM failed

- TensorRT-LLM failed after I rejected the Network request to Nitro
- We need to have clear directions on how to fix this (if user rejects network request)
- I'm ok with leaving this out, and focusing on Cortex TensorRT-LLM instead

![image](https://github.com/user-attachments/assets/69e8c1bc-cc7a-4d2b-9940-cbdf51546ac3)

**Comment by dan-homebrew** [comment]
0.5.4 Released.
