### ISSUE TITLE
roadmap: Jan has revamped Remote Engines (e.g. OpenAI, Anthropic etc)

### ISSUE THREAD

**Issue by dan-menlo** [janhq/jan#3786]
**Goal**

_Note: This Epic has changed multiple times, as our architecture has also changed
A lot of the early comments are referring to a different context
e.g. "Provider Abstraction" in Jan_

	• Cortex is now an API Platform and needs to route route `/chat/completion` requests to Remote APIs
		- This is intended to allow us to support Groq, Martian, OpenRouter etc
	• Remote API Extensions will need to support
		- Getting Remote API's model list
		- Enabling certain default models (e.g. we may not want to show every nightly model in Remote API's Model List)
		- Remote APIs may have specific model.yaml templates (e.g. context length)
		- Routing of `/chat/completion`
		- Extension should cover both UI layer, as well as "Backend" (we may need to modify Cortex to accept a Remote param)
		- Handling API Key Management
	• We may need an incremental path to Remote API Extensions
		- Cortex.cpp does not support Extensions for now
		- We may need to have Remote API Extensions define a specific payload, that Cortex `/chat/completions` then routes conditionally

**Tasklist**

**Jan**

- [ ] UI implementation https://github.com/janhq/jan/issues/4251
	- [x] UI update for Adding Remote Engines - pending @imtuyethan
	- [x] janhq/jan#3690
	- [x] Planning: Migration path for Jan's current Remote Extensions, and API Keys @louis-jan
	- [ ] Planning: Remote Engines registry @louis-jan @urmauur
		- Is there a github that we can have, with `transformReq`, `transformResp`
		- Similar to model catalog, but for Engines: https://github.com/janhq/engines
	• [x] Support for Prompt Caching:
		- https://github.com/janhq/jan/issues/3715
		- Settings UI

**Backend** 
- [x] https://github.com/janhq/cortex-internal/issues/15
- [x] https://github.com/janhq/cortex.cpp/issues/1662

**Remote APIs to Support**

_Popular_
- [x] OpenAI: https://github.com/janhq/jan/issues/3370
- [x] OpenRouter:
	• https://github.com/janhq/jan/issues/3110
	• https://github.com/janhq/jan/issues/3452
	• https://github.com/janhq/jan/issues/3582
	• https://github.com/janhq/jan/issues/2752
- [x] Anthropic (Claude):
		- https://github.com/janhq/jan/issues/3715
		- https://github.com/janhq/jan/issues/2752
- [x] Mistral

_Deprioritized_
- [x] Nvidia NIMs: https://github.com/janhq/jan/issues/3240
- [x] Google: https://github.com/janhq/jan/issues/3010
- [ ] Nvidia Triton Server (Remote)
- [x] Cohere
- [x] Github Models: https://github.com/janhq/jan/issues/3296
- [ ] Groq
- [ ] Deepinfra
- [x] Deepseek: https://github.com/janhq/jan/issues/3583
- [ ] Google API
- [ ] Together
- [ ] AI Horde
- [ ] Google AI Studio
- [ ] Featherless: https://github.com/janhq/jan/pull/3542
- [ ] Ollama: janhq/jan#2998

**Comment by dan-homebrew** [comment]
Goal: Clear Eng Spec for Providers

- "Provider" Scope
     - Remote (Groq, NIM, etc)     
     - Local = Hardware + APIs + Model Management (Ollama, Cortex)
     - It is possible that we don't need a differentiation between Remote and Local
     - Choosing a better name, vs. "OAIEngine")
- Provider Interface + Abstraction
     - Providers registers certain things (e.g. UI, Models), can be called by other extensions
     - Registers Settings Page
     - Registers Models Category + List
- Each Provider Extension should be a separate repo?
     - I would like this -> add others to help maintain

**Comment by louis-jan** [comment]
## Jan Providers

### Local Provider
Currently, the local extension still has to manage processes itself, which involves utilizing third-party frameworks such as Node.js (child_process) for building functions.

What if we build Jan on mobile we have to cover extensions as well. It would be better to move these parts to Core module and frontend will just need to use it’s API.

Local Provider will need to execute a command to run its program. Therefore, the command and arguments will be defined, while the rest will be delegated to the super class.

**Lifecycle**: 
- A Local Provider is intended to run engines as an API Server (potentially using HTTP, socket, or gRPC).
- Local Provider executes a command through CoreAPI (reducing the main process implementation from extensions, easy to port to other platforms such as mobile)
- Main Process core module will run a watchdog and maintain the process
- Since then, the app has been able to make requests and proxy through the Local Provider extension.
- App terminates -> watchdog terminates the process.

**Examples**

```ts
class CortexProvider extends LocalProvider {
  async onLoad() {
     // The Run is implemented from the core module
     // then the spawn process will be maintained by the watchdog
     this.run("cortex", [ "start", "--port", "39291" ], { cwd: "./", env: { } })
  } 

  async loadModel() {
    // Can be a http request, socket or grpc
    this.post("/v1/model/start", { mode: "llama3.2" })
  }
}
```

![Image](https://github.com/user-attachments/assets/7f56f1cb-6629-4360-b600-90062eb0f4ff)
> https://drive.google.com/file/d/1lITgfqviqA5b0-etSGtU5wI8BS7_TXza/view?usp=sharing

### Remove Provider
- The same as #3505
### Provider Interface and abstraction
- Providers are scoped at engine operations, such as running engines, loading models...
   - `registerModels(models)`
   - `run(commands, arguments, options)`
   - `loadModel(model)`
   - `unloadModel(model)`
- Core functions can be extended through extensions, not confined by providers, such as Hardware and UI.
   - `systemStatus()`
   - `registerSettings()`
   - `registerRibbon()`
   - `registerView()`

Registered models will be stored in an in-memory store, accessible from other extensions(`ModelManager.instance().models`). The same as settings. App and extensions can perform chat/completions requests with just `model` name, which means the registered model should be unique across extensions.

The core module also exposes extensive APIs, such as `systemStatus` so other extensions can access, there should be just one implementation of the logic supplied by extensions. Otherwise, it will merely be utilized within the extension, first come, first served.

The UI of the model should be aligned with the model object, minimize decorations (e.g. model icon), and avoid introducing various types of model DTOs.

**Comment by dan-homebrew** [comment]
@louis-jan We can start working on this refactor, and make adjustments on the edges. Thank you for the clear spec!

**Comment by louis-jan** [comment]
# Alternative Path 

## Shifting to cortex.cpp - No more Jan provider extension

1. It was a blocker where each provider introduced its own API schema. For example, Anthropic does not include system messages inside the message array. Support for a new remote provider requires a new extension to be installed.
2. Each remote provider registers their own pre-defined models, which seems inefficient.

## Thoughts?
- Should those extensions be able to be combined into one with very minimal functioning for proxying, so users can just add their own provider? Ref https://github.com/janhq/models/issues/23#issuecomment-2381136479 for the idea.
- How can we shift those to Cortex so it can share the same function with the BE and make Jan thinner and easier to deliver?

## Ideas
- Build on top of a popular config template so that users can share the config between Jan x Cortex and other ecosystems. Litellm for example has a configuration API that is really well-defined, so it's better to learn and build a function on top of that schema so that it can be used widely. Users can also edit the yaml file without requiring Jan up to be used (cortex support?)
- Templating payload transform so that users or maintainers can easily add or update a new provider support (in seconds?)
- By those two above, we can easily shift all the remote providers support to cortex easily. 

See the diagram for the ideas' visualization (The red lines means optional APIs, which are not required, we don't want to introduce a complicated API set)
![Screenshot 2024-10-31 at 14 57 17](https://github.com/user-attachments/assets/3070bcc8-78fd-488f-83fc-d39c7b75b962)

An example of a provider payload transformation template
<img width="1909" alt="Screenshot 2024-10-31 at 15 12 47" src="https://github.com/user-attachments/assets/dfa572f8-9fbc-4660-8760-e93499baf753">

## Results
- A dynamic yet simple remote provider support mechanism.
- Lightweight Jan
- A well-known configuration schema is used with provider model templating using Jinja so it can be configured easily from Jan but still scale the functionality from Cortex without requiring code additions.

**Comment by dan-homebrew** [comment]
@louis-jan @nguyenhoangthuan99 A random thought: is the correct long-term decision to build Remote APIs on the correct abstractions, i.e. Engines and Models? After reading the Jinja proposal above, I am worried that it is a hack that will simply introduce more complexity in the long term. 

I am more in favor of aligning the Engines abstraction to match @louis-jan's earlier Provider abstraction. I am not as deep in this as you guys, but wanted to brainstorm a few ideas out loud: 

From my naive perspective, we can have Engines that represent Remote APIs: 

## Transforming `/chat/completion` request into Remote API's format

- @louis-jan has already articulated the `transformPayload` and `transformResponse` above
- Engines representing Remote APIs transform the request and response from the API
- They handle API-specific param changes, e.g. turning on Claude's prompt caching
- They handle model-specific param changes, e.g. o1's model param changes

## Getting Remote API's model list

- `/engines/models` can return an engine's related models (e.g. to show in Jan's model dropdown)
- For Remote API endpoints, this would be a remote call
- We would still need to filter "major" models (e.g. not show every GPT-4 nightly model)

The Engine Interface we have designed can extend to handle this: 
- https://github.com/janhq/cortex.cpp/blob/dev/engine/cortex-common/EngineI.h

This would be a pain to do in C++, but I think with with a clear Interface spec and LLMs it may be doable. More importantly, it sets the correct architecture, which will not change when we switch to shipping Cortex Python.

**Comment by nguyenhoangthuan99** [comment]
# Remote Engines Specification

## Remote Engine Architecture
- Remote APIs are implemented as Engine abstractions, requiring a separate repository for remote API integration
- Each remote engine manages specific remote model types (OpenAI, Anthropic, etc.)
  - Each remote model corresponds to an engine type (e.g., OpenAI engine, Anthropic engine)
- Remote engines must implement all `EngineI` interfaces for their respective models
  - Implementation follows the pattern established in [llamacpp](https://github.com/janhq/cortex.llamacpp/blob/main/src/llama_engine.h#L10)

## Configuration Structure

### Engine Settings
Each remote engine maintains its own `settings.json`. Example OpenAI configuration:

```json
[
  {
    "key": "openai-api-key",
    "title": "API Key",
    "description": "The OpenAI API uses API keys for authentication. Visit your [API Keys](https://platform.openai.com/account/api-keys) page to retrieve the API key you'll use in your requests.",
    "controllerType": "input",
    "controllerProps": {
      "placeholder": "Insert API Key",
      "value": "",
      "type": "password",
      "inputActions": ["unobscure", "copy"]
    },
    "extensionName": "@janhq/inference-openai-extension"
  },
  {
    "key": "chat-completions-endpoint",
    "title": "Chat Completions Endpoint",
    "description": "The endpoint to use for chat completions. See the [OpenAI API documentation](https://platform.openai.com/docs/api-reference/chat/create) for more information.",
    "controllerType": "input",
    "controllerProps": {
      "placeholder": "https://api.openai.com/v1/chat/completions",
      "value": "https://api.openai.com/v1/chat/completions"
    },
    "extensionName": "@janhq/inference-openai-extension"
  }
]
```

### Model Configuration
Each model requires a `model.json` file to manage chat completion parameters. Example:

```json
{
  "sources": [
    {
      "url": "https://openai.com"
    }
  ],
  "id": "o1-mini",
  "object": "model",
  "name": "OpenAI o1-mini",
  "version": "1.0",
  "description": "OpenAI o1-mini is a lightweight reasoning model",
  "format": "api",
  "settings": {},
  "parameters": {
    "max_tokens": 4096,
    "temperature": 0.7,
    "top_p": 0.95,
    "stream": true,
    "stop": [],
    "frequency_penalty": 0,
    "presence_penalty": 0
  },
  "metadata": {
    "author": "OpenAI",
    "tags": ["General"]
  },
  "engine": "openai"
}
```

## File System Structure
Configuration files should be stored alongside remote engines in the cortex directory:

```
cortexcpp/
      engines/
            llama-cpp/
            remote/
                   libengine.so
                   anthropic/
                   openai/
                         settings.json
                         o1-mini/
                              model.json
                         o1-preview/
                              model.json
```

## Cortex-cpp Integration

### Engine Management API
- `/engines/list`: List available engines
- `/engines/install`: Install new engines
- `/engines/uninstall`: Remove engines
- `/engines/get`: Get engine details

### Model Management API
- `/v1/models`: List all available models (both local and remote)
  - Includes preset OpenAI models, and we can also allow user to add nightly models
![Image](https://github.com/user-attachments/assets/39d24c94-e3a4-419b-838b-2555d853133c)

  - Allows user-added models with OpenAI remote engine
- `/engine/models`: List all models associated with a specific engine

### Chat Completion
- Endpoint: `/v1/chat/completion`
- Handles both local and remote model requests
- Routes requests to appropriate engine based on model type

## Implementation Notes
- All remote model management is handled by their respective engines, not cortex.cpp
- Current logic for local models in cortex.cpp remains unchanged
- Configuration changes are isolated to the remote engines folder structure

**Comment by dan-homebrew** [comment]
@nguyenhoangthuan99 I would like to articulate a clearer idea of how we approach Engines, and to prepare for a future if Cortex is implemented in Python: 

- We have a very clear Engines abstraction, each of which have a separate repo
- Engines may have multiple implementations (e.g. C++ binary, and Python in the future)
- In the future, we may have a Python-based Extension framework that allows Python-based Engines to run on C++

Right now, we are focused on Cortex C++, and the output should be a C++ binary that is dynamically linked (i.e. how we do llama.cpp right now). 

Due to the tediousness of C++, I recommend we just focus on 3 key engines for our users (i.e. OpenAI, Anthropic), and then provide a generic OpenAI Engine that takes in a API URL and model name. Imho, most API providers should already have adopted the OpenAI standard.

**Comment by dan-homebrew** [comment]
One thing I'd like to clarify though - from my POV, we should have different engines for each: 

- anthropic-engine
- openai-engine
- llamacpp-engine
- tensorrtllm-engine

The Engine abstraction will need to be of `type: local` or `type: remote`. 

> # Remote Engines Specification
> ## Remote Engine Architecture
> * Remote APIs are implemented as Engine abstractions, requiring a separate repository for remote API integration
> * Each remote engine manages specific remote model types (OpenAI, Anthropic, etc.)

**Comment by nguyenhoangthuan99** [comment]
The Updated implementation will be simplified like this:
 
- Implement dylib for openai engine and Anthropic engine so cortex.cpp can load like the llamacpp engine
- Get models will call remote API and return info (model ID, name,...)
- ChatCompletion(will transform request) and forward to remote provider.
- Cortex will manage all api settings and model settings for remote provider

**Comment by imtuyethan** [comment]
This epic should solve:
- [ ] https://github.com/janhq/jan/issues/3745
- [ ] https://github.com/janhq/jan/issues/3448
- [ ] https://github.com/janhq/jan/issues/3520
- [ ] https://github.com/janhq/jan/issues/3851
- [ ] https://github.com/janhq/jan/issues/3889

**Comment by louis-jan** [comment]
@nguyenhoangthuan99 
- GetModels will call remote API and return info (model ID, name,...)
- Remote and local models will be handled consistently using model.yml files
- When call /v1/models/list, also return remote models and create model.yml if not exists.

*Would this cause significant latency for /models? It would result in a poor user experience for clients. Also it's `/v1/models` no `/list` path component.*

- Remote models are treated as extensions and will not be stored in the database, remote engine will manage its own models

*This would result in duplicate implementations between extensions. The current code-sharing mechanism between engine implementations is inadequate. My naive thought that you mean to scan thru the folder, but that introduce a bad performance as we tried to introduce the db file to optimize that. Otherwise, `open interpreter` would result in hundreds of model entries that cause a noticeable problem.*

3. HandleChatCompletion (will transform request) and forward to remote provider

*I think there should be a transformer for parameters to map to Jan UI and consistently persist model.yml.*

**Comment by nguyenhoangthuan99** [comment]
Updated base on Louis recommendation:

- we will implement separate endpoint for get model corresponding to engines `/v1/engine/models` and support filter for model name with remote engine

- Remote models will be saved in DB with different table `RemoteModels` and have follow fields: `model`, `engine`, `path_to_model_yml`, `path_to_engine_setting` -> we need to provide API endpoint for adding remote models, only added models are saved in DB

- remote engine setting (api key, url, ...) will be saved under `models/remote/` data folder, e.g. `models/remote/openai.json`, `models/remote/anthropic.json`, `models/remote/openai-compatible.json`... -> we need to provide API for engine setting `/v1/engine/setting`. 

- `model.yml` also contains mapping parameters fields for `params transformer`

**Comment by dan-homebrew** [comment]
> Updated `cortex.cpp` implementation base on Louis recommendation:
> 
> * we will implement separate endpoint for get model corresponding to engines `/v1/engine/models` and support filter for model name with remote engine
> * Remote models will be saved in DB with different table `RemoteModels` and have follow fields: `model`, `engine`, `path_to_model_yml` -> we need to provide API endpoint for adding remote models, only added models are saved in DB
> * remote engine setting (api key, url, ...) will be saved under `models/remote/` data folder, e.g. `models/remote/openai.json`, `models/remote/anthropic.json`, `models/remote/openai-compatible.json`... -> we need to provide API for engine setting `/v1/engine/setting`.
> * `model.yml` also contains mapping parameters fields for `params transformer`

@nguyenhoangthuan99 @louis-jan I am not sure about this implementation and would like us to brainstorm/think through more: 

## Overall 

- I would like to explore @louis-jan idea of more code-sharing between engine implementations
- One path I would like to explore is building a generic "Remote OpenAI-compatible Engine", and then letting users create instances of it.
    - URL
    - API Key
    - Transform Params
- We can probably incorporate elements of @louis-jan's proposal last week into the Engines abstraction

## Models

We should have a clear Models abstraction, which can be either local or remote. 

**`cortex.db` Models Table**
- I don't think a separate `RemoteModels` table in `cortex.db` makes sense; we should use the existing `models` table
- We should add a `remote` column which if `true` is a remote model
- `engine` should be a 1:1 to the remote engine
- Calling `/models` should return both local and remote, with field to indicate whether it's remote or local

Note: This will require us to implement a DB migrator as part of updater, which is an important App Shell primitive, as `cortex.db` does not have a `remote` column

**`getModels`**

One big question on my mind, is whether Models table should contain all remote models. What if OpenRouter returns all 700 models? What if Claude returns every claude-sonnet-<date> version? This would clog up Models table and make it impossible to use. 

- We should only be showing the "main" models (e.g. 3-4 main ones)
- We should still make it possible for the user to "define" a model they want to use, e.g. if they want to use `claude-sonnet-10082024`)

**`model.yaml` has the params transformer**
- I really like this idea, and think this is a very elegant way to deal with this
- We can host these in the Cortex Huggingface Org, as `model.yaml` for Remote models

## Engines

- I think remote engine settings should be stored in the `/engines` folder, not `/models`
- e.g. `/engines/anthropic`, `/engines/openai`, `/engines/<name>`
- Models belong to Engines, and there should be a SQLite relation between them

**API Key and URL**
- I think Engines can have a generic `settings.json` in their `/engines/<name>` folder
- Local and Remote Engines can share this abstraction

## Generic OpenAI API-compatible Engine?

> This is riffing off @louis-jan idea last week, of just having a Transform

- We should allow users to create a new generic OpenAI-compatible API 
    - Creates `/engines/<name>` folder
    - Creates engine entry in `cortex.db`'s Engines table
    - Creates `/engines/<name>/settings`
        - Takes in URL, API Key
        - Takes in Transform params (this can be overridden if model has `model.yaml`)

This would allow us to provision generic OpenAI-equivalent API Engines.

**Comment by dan-homebrew** [comment]
Concept of how `cortex.db` Engine:

![Image](https://github.com/user-attachments/assets/54863983-4c71-4ad6-b1d1-bce34105aea5)

**Comment by gabrielle-ong** [comment]
Cortex Implementation [WIP]: https://github.com/janhq/cortex.cpp/issues/1662

**Comment by dan-homebrew** [comment]
## 12 Dec

- [ ] Anthropic should not require a separate C++ file (we should amend the `transformReq` abstraction)

**Comment by vansangpfiev** [comment]
Engines -> Models List

- Status quo
  - Jan
    - We define/bundle everything in codebase
  - Cortex
    - We are currently defining remote models in Cortex Model Hub
    - Very manual, not ideal
    - This defines API routes and model.yml
   
All the fields in the model.yml can be generated with default value. Cortex can generate those model.yml files for each engine when user request to set up.

![image](https://github.com/user-attachments/assets/00e16b51-1f55-432f-a803-4b093e3d8839)

cc: @dan-homebrew @nguyenhoangthuan99
