### ISSUE TITLE
roadmap: Jan refactors `/messages`, `/threads` to Cortex

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/jan#3895]
## Goal

- Jan should be a thin UI layer
- Cortex should be an API Platform that has full OpenAI compatibility
- We need to itemize and shift functionality to Cortex (e.g. Threads, Messages)

From my POV, Jan should only be a UI and "Packaging" layer (i.e. Mobile, Desktop, Server)
All other API functionality and state should shift to Cortex

### Frontend
- [x] Itemize functionality that needs to shift to Cortex

### Backend
- [x] https://github.com/janhq/jan/issues/3825
- [x] https://github.com/janhq/jan/issues/3904
- [ ] https://github.com/janhq/cortex.cpp/issues/1567

### Administrative

- [ ] Dan/Nicole to link Internal/Admin issues

### Product Marketing

- [ ] @eckartal to link Content Calendar issues

## Resources

**Comment by gabrielle-ong** [comment]
WIP - Preliminary notes from last week with Louis

#### Model Hub 
- Updated models, delist 
- Jan dogfoods this to display on UI
- future: eg `Cortex remote models list`

#### View RAM, CPU usage 
- requires reimplementing `cortex ps` for each engine 
- Can be deployed first but currently combines all engines together resulting in inaccurate 

#### Hardware, eg GPU support
- #1165 
- Major Epic, needs thorough planning
- cortex.cpp needs hardware detection, currently doesnt support multi-GPU
- Major usage for Jan

#### Support Tensorrt-llm engines [Prioritised?]
- Need to define Model artifact, model.yml
- need to bundle artifacts (needs investigating)

#### multi-modal - cortex.cpp needs to be able to pull 2 models at the same time
- Need to define model.yml for the models

**Comment by imtuyethan** [comment]
- Bugs will be scoped in https://github.com/janhq/jan/issues/4291 if there's any
