### ISSUE TITLE
roadmap: Jan has Hardware Controls and System Monitor and Prioritization

### ISSUE THREAD

**Issue by dan-menlo** [janhq/jan#3908]
## Goal 

- Migrate Jan's Monitoring and Hardware Compatibility APIs to Cortex
    - e.g. System Monitor
    - e.g. Model Compatibility

### Out-of-scope

- [ ] AMD GPUs
- [ ] Intel GPUs

### Issues
- [ ] https://github.com/janhq/jan/issues/3908

### Frontend
- [ ] Designs & UI Engineering: https://github.com/janhq/jan/issues/3688
    - Prioritization of Nvidia hardware @imtuyethan `[0,1,2] || [id1, id2, id3]`

### Backend
- [ ] https://github.com/janhq/cortex.cpp/issues/1165
- [ ] https://github.com/janhq/cortex.cpp/issues/1568
- [ ] https://github.com/janhq/cortex.cpp/issues/1108
- [x] https://github.com/janhq/cortex.cpp/issues/1679
- [ ] https://github.com/janhq/cortex.cpp/issues/1458
- [ ] https://github.com/janhq/cortex.cpp/issues/1457
- [ ] #3529

**Comment by dan-homebrew** [comment]
## 12 Dec

### Hardware UI

![Image](https://github.com/user-attachments/assets/c6f990cf-d51e-49a3-be70-d52414ab6983)

### Open Questions

- [ ] How do we prioritize across both Nvidia and AMD GPUs?
- [ ] UX for Vulkan (as it can run on both Nvidia and AMD)
- [ ] Should we have separate settings for llama.cpp Engines and Hardware (eg. for Vulkan)

**Comment by vansangpfiev** [comment]
```
How do we prioritize across both Nvidia and AMD GPUs?
```
AMD and Nvidia have `uuid` field, we can use this field to map between GPU and the index we pass to `CUDA_VISIBLE_DEVICES` and `GGML_VULKAN_DEVICE` env variable.

**Comment by dan-homebrew** [comment]
@vansangpfiev Please add in architecture diagrams and Engineering Spec

**Comment by vansangpfiev** [comment]
- Diagram to configure global GPUs prioritization 
- Vulkan can detect both AMD GPUs and Nvidia GPUs
- Nvidia-smi can only detect Nvidia GPUs
- We have a mapping function to map `uuid` with `cuda index` and `vulkan` index

![image](https://github.com/user-attachments/assets/8e0aa5ab-64e2-43f1-82b9-4be66ea88ba8)

cc: @dan-homebrew @louis-jan

**Comment by imtuyethan** [comment]
Working great! 

![Image](https://github.com/user-attachments/assets/783f0674-e93b-4cd2-817a-8b4d0c6a7505)
