### ISSUE TITLE
roadmap: Migrate Jan's legacy Assistants to Cortex `/assistants` API

### ISSUE THREAD

**Issue by dan-menlo** [janhq/jan#3909]
## Goal 

- Jan's Assistants to migrate to Cortex `/assistants` API
- We are using the outdated Jan Assistant
    - Each thread will has a specific Assistant
    - Assistant has model settings (not ideal)

### Out-of-scope

- OpenAI-compatible Assistants
- Relies on `runs` to integrate into `threads`

### Backend
- [ ] https://github.com/janhq/cortex.cpp/issues/1573
- [ ] Decouple `threads.json` into Assistants: https://github.com/janhq/cortex.cpp/issues/1567#issuecomment-2444740659
- [ ] Add the OpenAI-Header =assisstant-v1

### Docs

- [ ] @namchuai 

## Scope 

- Default Assistant?
- Include Retrieval Tool?

**Comment by dan-homebrew** [comment]
Current state: 
- Each Thread has its own Assistant
- We need `runs` for Asssistants (global) to work with Threads

**Comment by dan-menlo** [comment]
Merging into https://github.com/janhq/jan/issues/4274
