### ISSUE TITLE
[spike] redesign app (formerly plugin) manager and life cycle

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#403]
## Problem

There is a few issue with the current app plugin manager and its lifecycle:

- It looks for the activation entry (defined in package.json) and activate instead of a registered instance
- How to know registered functions belong to which plugin?
- How to manage app lifecycle? its not an object, can't access this/its variables -> how to manage its variables and resources? memory leak?
- How to inherit common lifecycle methods? (onload, unload, constructor)
- How to manage its registered views, modals, ribbons?

Updated: Oct 30
- Stateless plugin / apps
- Less dependence on the database system

We need to redesign the App system

![Image](https://github.com/janhq/jan/assets/133622055/8c5a596b-bb71-4a25-aed7-209adab9e96f)

**Comment by louis-jan** [comment]
related issue #379

**Comment by louis-jan** [comment]
related issue #402

**Comment by louis-jan** [comment]
Updated - Oct 30

- Stateless plugin / apps
- Less dependence on the database system

**Comment by louis-jan** [comment]
![Image](https://github.com/janhq/jan/assets/133622055/39894a73-5f8e-43dc-babc-6667fc4f7d36)

**Comment by louis-jan** [comment]
@namchuai: 

Revamp plugins to not depends on @janhq/core/store:
- Conversations & messages -> conversational plugin -> file/json store? candidate: lowdb
- Model Management using json manifests (available state, tags...)
- App Preferences using json manifests
- Filesystem apis (core/fs)
- Core/inference api

**Comment by louis-jan** [comment]
@louis-jan:
- Revamp plugin management -> plugin as class, lifecycle

**Comment by louis-jan** [comment]
- [x] Revamp plugin management -> plugin as class, lifecycle
- [x] Filesystem apis (core/fs)
- [x] Revamped conversation plugin

**Comment by louis-jan** [comment]
- [x] Revamp Inference plugin
- [x] Revamp monitoring plugin

**Comment by louis-jan** [comment]
There are 2 conversational plugins that ready to install: 
- Conversational as Markdown
- Conversational as Json

**Comment by louis-jan** [comment]
There are many possible structures in the HackMD proposal, to summarize the appropriate approach for various checkpoints:

Currently, since the plugin handles application logic until the app and SDK are available, we use a flattened structure:
- conversations /
     - jan-[date]
         - jan-date.[md/json] the format depends on the installed plugin (this may be deprecated later when the app is ready to handle these logics)
- models / 
- plugins / 

Later, when apps and SDKs are available to manage the interface and logic, we may consider adopting a 'deep shallow' structure where everything can be organized under any app. The plugin will then simply provide importable modules or wrappers (running completely from the server-side [e/n]).

- luffy 
   - conversations // belong to this app

**Comment by louis-jan** [comment]
Model plugin: 
- downloadModel: Downloads a machine learning model
- deleteModel: Deletes a machine learning model
- getDownloadedModels: Saves a machine learning model
- getConfiguredModels: Gets all downloaded models

Downloaded models will be in 
App Data / Jan
- models 
   - [model-file].bin
   - [model-file].json

**Comment by louis-jan** [comment]
Updated Nov 6: 
- Since fs module now support rmdir, new model management update will be 
- models
     - [model-id]
         - model-id.bin
         - manifest.json

**Comment by louis-jan** [comment]
this is finished
