### ISSUE TITLE
roadmap: Jan Local Engine Management can pick Version and Variant

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4128]
# Problem Statement

https://cortex.so/api-reference#tag/engines/get/v1/engines/{name}
Jan needs a UI to manage Cortex.cpp engines based on the following API endpoints:
- List installed engines
- Install/Uninstall engines
- Load/Unload engines
- Get/Set default engine variant
- Update engine

### Issues
- [ ] https://github.com/janhq/cortex.cpp/issues/1469

### Jan Tasks
- [x] https://github.com/janhq/jan/issues/3913
- [x] https://github.com/janhq/jan/issues/4025
- [ ] https://github.com/janhq/jan/issues/4250
- [x] https://github.com/janhq/jan/issues/4337

### Cortex Backend Tasks
- [x] Implementation: https://github.com/janhq/cortex.cpp/issues/1416
- [x] Enhancement: https://github.com/janhq/cortex.cpp/issues/1684
- [x] engines update: https://github.com/janhq/cortex.cpp/issues/1638

# Feature Idea
https://cortex.so/api-reference#tag/engines/get/v1/engines/{name}

**Engine Management**
- Version
- Update: Update engine to latest version of current default variant
- Set Default: Ability to set default variant for each engine type
- Show installed engines with:
  - Engine type (llama-cpp, onnxruntime, tensorrt-llm)
  - Variant name (e.g., mac-arm64, linux-amd64-avx)  
- Only one engine can be loaded at a time
- Handle errors gracefully
- Install: Allow installing specific engine variant/version 
- Uninstall: Remove engine variant
