### ISSUE TITLE
Proposal for Jan.ai Structure

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#512]
## Objective

- User should be able to read https://jan.ai and understand Jan's purpose (and Nitro's)
- Open source contributor should be able to read https://jan.ai and READMEs to understand how codebase is architected
- [Later] Developer should be able to read https://jan.ai to understand how to build Apps on Jan

## Todos

- [ ] Get all diagrams from engineers (e.g. @louis-jan @vuonghoainam @tikikun)
- [ ] Brainstorm with Daniel on docs structure 
- [ ] Architecture section (big picture)
- [ ] Contributing section
- [ ] Developer section (i.e. App, Plugin, etc)

**Comment by dan-jan** [comment]
Migrated:
https://github.com/janhq/chores/issues/10
