### ISSUE TITLE
[Research] Bot "Standards"

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#514]
## Objective

- There are emergent "Bot" formats that can be downloaded and used across SillyTavern, Pygmalion etc
- We should build upon this as we think through Apps

## Todos

- [x] https://www.reddit.com/r/PygmalionAI/comments/17kgb2p/i_made_a_page_where_you_can_search_download_bots/
- [x] Understand how bots can be imported into Sillytavern, Agnai, RisuAI, VenusChub, Venus
- [ ] Understand how bots are distributed via Faraday's Character Hub, Janitor.ai etc
- [x] Strategy for how we can build on this for our "App" framework

**Comment by hahuyhoang411** [comment]
The "App" framework should be divided into 2 main purposes:
1. **Characters:** entertainment (Anime characters, Hollywood, Idols,...) (Just pop up in mind, is it normal for users to have a group chat with humans and bots?)
2. **Productivity:**
2.1. Education: Explain docs/thesis/paper, Search for papers, Paraphrase, Make quizzes...
2.2. Kids: Answer 1001 questions about the world (with SD images),...
...

I think we should have a set of recommendation plugins when users create apps. For example,
Users -> Create bot for making MCQ -> We pre-enabled RAG + Good system prompts as a default -> They could also add more "Apps" (like Search Internet) or config the prompt, etc.

**Comment by dan-jan** [comment]
Migrated to https://github.com/janhq/chores/issues/7
