### ISSUE TITLE
analytics: Landing page analytics checklist 

### ISSUE THREAD

**Issue by tikikun** [janhq/jan#690]
**Problem**
We need proper tooling and system to track landing pages and possibly some parts of the app to have the overall view about the project

**Success Criteria**
- [x] List of events cho jan app   
- [x] Custom tracking events that needs to be implemented on pages  
- [x] SEO - Catch up with @hiento09 on
- [x] GA - Will need to check if it is required for landing page and SEO -> conclusion, no need
- [x] Nitro landing page dashboard: https://app.posthog.com/dashboard/112758
- [x] Jan landing page dashboard: https://app.posthog.com/dashboard/112763
