### ISSUE TITLE
chore: Prepopulate Jan's /models folder with `model.jsons` of Recommended Models

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#709]
## Objective

- Jan ships with a list of "Recommended Models", which are implemented as `model.jsons` in the `/model` folder that point to GGUF binary downloads
- We should make recommendations for different levels of users' hardware
    - e.g. 4gb RAM on laptops = TinyLlama
    - e.g. 8gb RAM = Mistral 7b q4?
    - e.g. 16gb RAM = ?
    - e.g. All the way to crazy people with 192gb RAM

Bear in mind, you will be choosing the Model and the Quantization. 

- You should treat every quantized model as "specific"
- e.g. for 8gb RAM, we recommend `mistral_7b_q3_k_m`. 
- Quantization has such a big impact on model quality and should not be interchangeable

## Task

- [x] Define list of "Recommended Models" for every step function of RAM or VRAM
- [x] Work with App Pod to ensure that `model.jsons` for Recommended Models are auto-created in `/models` folder when Jan is installed or updated
- [x] Deprecate https://github.com/janhq/models (old repo)

#### Folder Structure

```bash
# /models folder
/jan
    /models
        /llama2
            model.json
            # no GGUF or bin file
```
#### r/localllama

Popular models you can consider adding: https://www.reddit.com/r/LocalLLaMA/s/LDzwT3B7Ce

**Comment by hahuyhoang411** [comment]
https://hackmd.io/KyC0EBKiTbqZuKkx7FYVjQ?view

**Comment by louis-jan** [comment]
cc @namchuai for the
- Work with App Pod to ensure that model.jsons for Recommended Models are auto-created in /models folder when Jan is installed or updated
- Deprecate https://github.com/janhq/models (old repo)

**Comment by louis-jan** [comment]
no OTA update ^

**Comment by hahuyhoang411** [comment]
Please check the draft PR for this issue here: https://github.com/janhq/jan/pull/775

**Comment by louis-jan** [comment]
This issue still open because old models repo should not be archived till next release.

**Comment by hahuyhoang411** [comment]
Finished this one.
