### ISSUE TITLE
feat: Create Assistants with custom Instruction

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#732]
**Success Criteria**
- Assistant is folder based, OpenAI compatible and has refreshed UI.
- For this epic, focus on Assistants that take a custom System Prompt (or Instruction), non-RAG

**Full specs**
- https://jan.ai/specs/assistants
- https://jan.ai/api-reference/#tag/Assistants

## Tasks

There are quite a few open questions that we need to answer from Product standpoint. 

_Product Questions_
- [ ] Hub should support Assistants to download (where is the source?)
- [ ] Creating an Assistant
- [ ] Editing an Assistant (?)
- [ ] Using a created Assistant (straightforward, or...?)

_Processes_
- [ ] Docs for Assistant Framework
- [ ] Announcement for Assistant Framework
