### ISSUE TITLE
epic: Jan supports multi Inference Engines

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#751]
## Linked Milestone

https://github.com/janhq/jan/milestone/21

## Objective

- Jan's architecture will default to Nitro, but have flexibility to incorporate other Model Backends / Inference Engines
- We see very fast movement around a few ecosystems
    - [Intel BigDL](https://github.com/intel-analytics/BigDL)
    - [Intel Extensions for Transformers](https://github.com/intel/intel-extension-for-transformers)
    - [TensorRT-LLM for WIndows](https://blogs.nvidia.com/blog/ignite-rtx-ai-tensorrt-llm-chat-api)
    - And many more to come
- Jan's Architecture needs to be able to incorporate modular Inference Engines
    - Parallelize efforts to support different inference engines
    - Allow us to hedge technical architectural risks 

## Tasklist

- [x] #913 
- [x] #771
- [x] Extensions: `model extension`, `inference engine extension` - #783 
- [x] POC using OpenAI API endpoint as a "remote" inference engine - #783
    - [x] Users should be able to set `model.json` parameters
    - [x] Inference engine should have defaults
- [x] Refactor Nitro into a "default" inference engine - #783
- [ ] Think through app default behaviors
    - [ ] What happens when there's no internet
    - [ ] What happens when users don't set `engine` for their GGUF/GPT model? (obv)
- [ ] Documentation
    - [ ] Docs for Model Extension
    - [ ] Docs for Inference Extension
    - [ ] Docs for inference-engine-*

## Related Epics
- #761 
- #762

**Comment by vuonghoainam** [comment]
1. Idk what models extension do when we have flat and separate model extensions
2. Nitro and anything as remote models (oai/ azure oai/ claude/ tgi compatible) will be supported by Dec 15
3. I will check if the nvidia local llm support or not but this is optional, but as in their announcement the 0.6.0 will be out in 2023 Dec.

**Comment by A2va** [comment]
There is also the mlc-ai backend which might be interesting.
https://github.com/mlc-ai/mlc-llm

**Comment by tikikun** [comment]
Stale, rn we're doing this in cortex with different ticket
