### ISSUE TITLE
feat: Threads can override and inherit default params from Assistants, Models, and Engine

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#754]
## Tasks

- [x] Eng Spec @dan-jan 
    - [ ] Local Models
    - [ ] Remote Models (KIV)
- [x] janhq/internal#66
- Functionality
    - [x] Each Recommended Model should have default values defined in respective `model.json`
- Documentation
    - [ ] Architecture section should contain page on relationship between `Threads`, `Assistants`, `Models`, `Engines`. 
    - [ ] Docs page on Models Extension, 
    - [ ] Docs page on Inference Extension
    - [ ] Docs page on Engine extensions
- [ ] API Reference (i.e. Swaggerfile)
    - [ ] `model.json` params are well documented in Swaggerfile
    - [ ] `assistant.json` params are well documented in Swaggerfile
    - [ ] `engine.json` params are well documented in Swaggerfile

## Spec

<img width="1119" alt="image" src="https://github.com/janhq/jan/assets/101145494/49eed63b-75a2-4f40-b552-dde802568212">

### Overview

- Threads are a core primitive in Jan, and the main means by which a user will interact with AI
    - A Thread is defined as an exchange between a User and an Assistant
- A thread uses default params that are specified for that Assistant (and its associated Model(s) and Engine(s))
    - A user may choose to override these default params
    - Assistant params are inherited from `assistant.json`
    - Model params are inherited from the `assistant.model`'s `model.json`
    - Engine params are inherited from `model.engine`'s `engine.json`
- The Thread UI offers an optional, slide-in "Right Panel" that allows the user to tinker and change params
    - Any user-specified, thread-level params are persisted in an associated `thread.json`
    - `thread.json` is usually empty, as it auto-inherits properties from the associated defaults
- The Thread UI should prompt the user to "Reload" the model + engine if required
    - Model Params and Engine Params will usually require reload
    - We should find way to "automatically" reload it, if user sends new message to Assistant

### Wireframes

<img width="1232" alt="image" src="https://github.com/janhq/jan/assets/101145494/597cb448-6da8-49fd-98f1-429d5be48cfa">

<img width="1241" alt="image" src="https://github.com/janhq/jan/assets/101145494/d6afdee1-0333-4bda-a9f5-094987a67019">

<img width="1170" alt="image" src="https://github.com/janhq/jan/assets/101145494/cd00859d-3ae9-483d-874a-0c29c0900df4">

<img width="1261" alt="image" src="https://github.com/janhq/jan/assets/101145494/c37f99a1-680a-4adc-a9e9-98f086ac6eaa">

Excalidraw: 
https://link.excalidraw.com/l/kFY0dI05mm/3WHim5p2OLu

**Comment by dan-jan** [comment]
![Image](https://github.com/janhq/jan/assets/101145494/eccbe9db-7a89-4099-881e-54fc10e884d1)

![Image](https://github.com/janhq/jan/assets/101145494/2e4fb8b1-a51c-4cf3-a2bd-33a99ee8f91b)

**Comment by dan-jan** [comment]
See LiteLLM's approach to prefix, suffix and roles and prompt templates


https://github.com/abetlen/llama-cpp-python/issues/717#issuecomment-1722093969

![Image](https://github.com/janhq/jan/assets/101145494/d8ae914c-f279-48ca-8e90-cf8a62aeea0a)

**Comment by dan-jan** [comment]
One question is also whether there should be a "Hardware Settings", e.g. for Apple Silicon users? 

https://www.reddit.com/r/LocalLLaMA/comments/186phti/m1m2m3_increase_vram_allocation_with_sudo_sysctl/

**Comment by tikikun** [comment]
@dan-jan for current release there will be no different in settings for different hardwares, mostly already automatically handled at build time

**Comment by tikikun** [comment]
Q:Where are these prompt template coming from?
<img width="787" alt="image" src="https://github.com/janhq/jan/assets/22268502/e4f8fadc-ad57-471b-ae9f-0b7b4863b234">

Most of community projects now using TheBloke metadata as referrence

https://huggingface.co/TheBloke/LLaMA2-13B-Psyfighter2-AWQ#prompt-template-alpaca-tiefighter

<img width="879" alt="image" src="https://github.com/janhq/jan/assets/22268502/4594b379-36cc-4731-b7c8-866bec3421f4">

**Comment by tikikun** [comment]
We will have 2 main modes: LOCAL and REMOTE

LOCAL
<img width="1182" alt="image" src="https://github.com/janhq/jan/assets/22268502/ba62fb6f-b9f0-4e2e-bc79-949bb8f990b2">

REMOTE
<img width="561" alt="image" src="https://github.com/janhq/jan/assets/22268502/9a5a37dc-1999-4cc9-9e7e-eda796263f2a">

**Comment by tikikun** [comment]
Link to excalid draw:
https://excalidraw.com/#json=kOBPg9OoLTCLAm3JO7FHn,qV29wMh7fLvGkFXf5HRYNA

**Comment by 0xSage** [comment]
Asks: 
1. Can we the settings properties in swagger/json schema (with validation, etc).
2. A list of prompt templates (so users can have a dropdown selector)

schema fields
```js
id: 
type: 
required: boolean
data_validation: {
  min: 
  max:
}
default:
information: // (i) that tells users what this field actually does
```

**Comment by 0xSage** [comment]
Discussion updates: 

Based on: https://app.excalidraw.com/s/kFY0dI05mm/3WHim5p2OLu

1. Assistant Section: Add back the model selector
- Users should be able to choose a model to chat with when using Jan assistant.
- Remember: users can only change models at the beginning of a thread, not after thread has started
- So we need to also show a change-model-disabled-state in designs.
- Remember: the model determines the variables in the next sections: `inference parameters`, `model params` `engine params` content may change depending on the model chosen.

2. Users can change `Assistant Instructions` aka the `system message`
- Users can edit assistant instructions after conversation starts.
- We briefly discussed sending a new “system message updated... etc.” In the MainPanel. Ashley will play around with a potential design for it.
- The `system message` may show up in MainPane differently, not as a regular message sent from the user, but as a little box/styled differently?
- Again, this is a nice to have. It's possible we don't show anything related to it in the MainView at all

3. We shouldn't auto save when users edit each field. We should make users click a global `save` button, which saves all sections at once.
- Reason: reduce fs writes to `thread.json`
- See (4)

4. Users must restart model after editting `model_params` or `engine_parameters`
- If users edit `model_parameters` & `engine_parameters`, then they have to `save & restart model`, a two step process. @imtuyethan will play around with how the designs communicate this.
- These 2 sections should say “requires model restart” somewhere...

5. Alan is working on parameter fields, like mins/max/etc.

6. `Model Parameters` section UI
- “Prompt Template” is a drop down where ppl can choose from different templates
- Example 1: https://huggingface.co/TheBloke/meditron-7B-GPTQ#prompt-template-chatml
- Example 2: https://huggingface.co/TheBloke/SlimOrca-13B-GGUF#prompt-template-ajibawa-assistant 
- UI wise, just show the `prompt template` as in a plain text box. Advanced users can directly edit the text. Do not highlight : “{prompt}” “{system_message}”, or do anything fancy like Daniel suggested XD.
- Have a reset button so ppl can undo if they mess up. Reset button goes back to assistant.json defaults

7. Actually play around with having a reset button for each sections, at the section level (not global)

8. @Rex make sure every model has a prompt template filled in

9. Alan TODO later: low fidelity mock on how “model.json settings is different than thread.model.json settings”

10. Remote model side panel - we didn't discuss this as much. Punt till later

**Comment by 0xSage** [comment]
@imtuyethan 

A note on the menu items, I saw that we currently open up `model.json` `assistant.json` when users click "Reveal in Finder/JSON" in all the sections.

It should be

- Every section: "Reveal in finder/View as JSON": opens `threads.json
- "Change Default*** Model/Assistant Settings": opens Model/Assistant settings page


![Image](https://github.com/janhq/jan/assets/69952136/ab5ef31b-43e6-43c9-b8e3-8d8261ae5cac)

**Comment by namchuai** [comment]
@imtuyethan , please help to verify this.
cc @louis-jan
