### ISSUE TITLE
epic: Jan Desktop API server @localhost:1337

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#773]
# Motivation
To establish an API server locally on localhost:1337 that interacts with the Jan Desktop application.
- Provide an API endpoint & facilitate direct server calls for additional functionality and operations.
- Create a user-friendly interface for seamless interaction and comprehension of the API server functionalities.

## Leads
- Product: @imtuyethan 
- Engineering: @louis-jan 

## User Stories
_In Scope_

1. **Model Selection:**
   - As a user, I want to choose which model I want to make available at https;//localhost:1337 as an API

2. **Server Configuration Options:**
   - As a user, I want to customize the server port to ensure compatibility with my system's setup.
   - As a user, I want to manage Cross-Origin-Resource-Sharing (CORS) settings to control access permissions for security reasons.
   - As a user, I want the option to enable or disable verbose server logs for effective debugging and troubleshooting.

3. **Examples (Request, Response, etc.):**
   - As a user, I want access to clear examples of API requests and responses for better understanding and usage guidance; and if possible, a link to Jan's API docs for more details.

4. **Server Logs:**
   - As a user, I want access to detailed and comprehensive server logs, providing in-depth information about each API request and response for thorough debugging and analysis.
   - As a user, I want a dedicated section displaying API metrics, offering insights into usage statistics, response times, and other relevant performance indicators for better optimization and monitoring.

_Out-of-Scope_
- System Monitoring

## Design Wireframes

Figma link:

## Engineering & Architecture

_In Scope_

- Jan Server will have automatical model loading/unloading based on incoming requests
- User can call /chat/completions with any model that is available
- API Server will have some sort of inference queue
- Jan will automagically switch between models based on /chat/completions queue
We may do some optimizations (e.g. batch inference etc)

- Jan Enterprise can be run in "headless" mode
- There are quite a few use-cases now that I realize we should recommend Jan instead of Nitro (e.g. Z wanting to run a backend process for a LLM to mark student essays, generate questions from IELTS text etc).
- Jan Enterprise will likely prioritize the "API Server" use case, much less the UI

_Out-of-Scope_

# Tasklist
- [x] #1123 
- [ ] #1251 @urmauur 

# Resources
https://jan.ai/api-reference/#tag/Chat

# Out of scope

**Comment by dan-jan** [comment]
Questions: 
- Should we combine System Monitor and API Server (or should they be separate)

**Comment by imtuyethan** [comment]
Archive Dan's original comment:

## Linked Milestone

https://github.com/janhq/jan/milestone/12

## Motivation
- Works with Jan Desktop
- Tab for server stuff
- UI for helping users understand potential concurrency issues etc.

## Questions: 
- What can users do concurrently, i.e. via desktop client and direct server calls?
- Do we need to disable features?

## In Scope

Stop-gap UX when it comes to concurrent usage of desktop client & local server. 
- Long term, we need to handle both scenarios
- How to handle multiple models, loading, unloading?
- It should work like openai, where the endpoints are smart about it.
- [ ] #1123
- [ ] Can we run multiple models at once?
- [ ] How will this work with multiple inference engines (e.g. TensorRT-LLM, etc)
- [ ] What does https://localhost:1337 show? (Swagger UI?)

## Not in Scope 
Long term questions.
- Jan/Nitro to handle inference queue and auto switch models
- Supporting multile inference engines


## User Stories

## Wireframes

## Engineering Architecture

## Future Work

**Comment by 0xSage** [comment]
Done

**Comment by 0xSage** [comment]
Tracking next steps via: #1235
