### ISSUE TITLE
epic: Refactor Jan with clear Extensions and Modules Architecture

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#778]
## Todos

- [ ] Rename "Plugins" to Extensions or Modules
- [ ] Document Extensions and Modules Architecture
- [ ] Document key Extensions (e.g. Models, Inference, Threads etc)
