### ISSUE TITLE
feat: Hub has two featured models and is sorted by size

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#860]
## Spec

- Hub should display models sorted in following order:
    - Featured models (the two with cover images)
    - 7b
    - 13b
    - 33b
    - 70b
    - "Tiny" (last)
- Hub should have two "recommended models" which we've already tested and provide great experience
    - Mistral 7b Instruct (cover image so it's bigger)
    - OpenHermes Neuralchat 7b q4 (cover image so it's bigger)

## Tasks

- [x] Create cover images for Mistral and NeuralChat @imtuyethan 
- [x] Update Model.jsons @hahuyhoang411 
- [x] Update Hub ordering @louis-jan @urmauur 
- [x] Ensure Cover image shows up in Hub @louis-jan @urmauur 

---
## Legacy Specs

**Problem**
Eventhough we have a recommendation tags, we should also have “featured model” for users to know the best model to use

**Success Criteria**
Adding 2 featured models at the top of the hub
1. Mistral 7B Instruct
2. Openhermes Neural 7B

**Comment by dan-jan** [comment]
@hahuyhoang411 Can we use Neuralchat 7b instead of Openhermes (has the newline issues?)

@imtuyethan Can we implement a cover image for both of them?

**Comment by imtuyethan** [comment]
Figma link: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=173-2428&mode=design&t=EZfZOgn0Rdcw2Qdu-4
cc @urmauur 

Images link: https://drive.google.com/drive/folders/13HAk_PMALgl0mTvjZNfJLHf3bZ8Eoq3j?usp=sharing

**Comment by urmauur** [comment]
@hahuyhoang411 @louis-jan https://github.com/janhq/jan/pull/872 Finished UI for cover image

**Comment by hahuyhoang411** [comment]
It's done for now.
