### ISSUE TITLE
epic: Jan as a ChatGPT alternative

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#955]
## Issues

https://github.com/orgs/janhq/projects/5/views/7?filterQuery=milestone%3A%22Jan+as+the+default+Assistant%22

## Epics (that belong to other roadmap)

_Questions_
- [ ] Per-conversation RAG (upload doucment)
- [ ] Jan can "route" tasks to the correct AI Model? (Function Calling?)
- [ ] Jan can produce images?
- [ ] #294 
- [ ] #295 

## Future Work

**Comment by 0xSage** [comment]
Closing in favor of better projects organization.
