### ISSUE TITLE
epic: Jan has better Hardware Monitoring (e.g. Prometheus Exporter, etc)

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#956]
## Kanban

https://github.com/orgs/janhq/projects/5/views/7?filterQuery=milestone%3A%22Jan+has+System+Monitor%22

## System Monitor

_Questions_
- [ ] Are we able to do a Prometheus/Grafana-style time series dashboard? (How do we even persist the data on flat files?)
- [ ] Or: do we ship with a Prometheus exporter for Jan Server implementations

## Tasklist

- [ ] https://github.com/janhq/jan/issues/287
- [x] https://github.com/janhq/jan/issues/286
- [ ] https://github.com/janhq/jan/pull/663

**Comment by namchuai** [comment]
@dan-jan , I'm not proficient with Prometheus and Grafana yet so will need to play with it a bit.
I do see that Prometheus has a npm package: https://github.com/siimon/prom-client which can help us to export metrics to Prometheus.

**Comment by namchuai** [comment]
According to our discussion with @louis-jan @vuonghoainam , we are about to packaging prometheus binary into Jan's extensions (just like how we did with nitro).

Jan will serve metrics at `:1337/metrics`

High level design:
![CleanShot_2023-12-18_at_11 17 41](https://github.com/janhq/jan/assets/10397206/3f2c52fc-2611-43c5-8cd9-4b4293ed1cd0)

Work breakdown
- [ ] Integrate with prom-client (npm package) and serve metrics at :1337/metrics
- [ ] Packaging Prometheus binary according ABI (mac/windows/linux and corresponding chip arm/x86)
- [ ] Define metrics that are needed (RAM, CPU, GPU usage, etc.)
- [ ] Collect those defined metrics and expose it via :1337/metrics
