### ISSUE TITLE
feat: users have to explicitly turn on OpenAI and configure API Key

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#998]
**Describe the bug**
OpenAI models should not be pre-populated via by model extension like other, OpenAI extension will provision models and should be enabled by default.

Action Items:

- [ ] Disable OpenAI extension by default
- [ ] Models will only be populated after user enable the extension
- [ ] Proper error message, see #995 

**Expected behavior**
- Fresh install Jan
- Onboarding screen should lead me to download models
- I can go to settings and enable OpenAI
- I can engine settings there
- I can create thread with OpenAI model then

**Comment by 0xSage** [comment]
@imtuyethan this issue is a bit outdated. I know your latest designs show OpenAI by default but makes it much clearer that they need to put in an API key. I'll close this issue in favor of tracking the new designs in a separate issue.
